### ISSUE TITLE
Home Page shows no Campaigns when there are campaigns seeded

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1027]
when loading HomeController/Index, the page is displaying with no Campaigns
![image](https://cloud.githubusercontent.com/assets/2428993/17067034/df403164-5017-11e6-833c-f41228872f10.png)

looking at the view model before it's sent back to the view, there are six campaigns that were populated from a query handler:
![image](https://cloud.githubusercontent.com/assets/2428993/17066816/c195549c-5016-11e6-8fa6-b1a26426bf97.png)

so we should be showing these campaigns. 

Looking closer at \Home\Index.cshtml it looks like we're using knockout to populate the list of campaigns. Checking out the errors via Chrome's debugger, looks like knockout is throwing this error:
![image](https://cloud.githubusercontent.com/assets/2428993/17066955/74d6c9f0-5017-11e6-8cbc-54d2577a60f4.png)

Not being a javascript or a knockout guy, my initial **guess** is knockout can't "define" `ImageUrl` b/c it's included on each `CampaignViewModel` coming back in the list of campaigns
![image](https://cloud.githubusercontent.com/assets/2428993/17067497/ef0af8c0-5019-11e6-9b53-258ebbab4dc3.png)

and the `ImageUrl` used on `CampaignSummaryViewModel`.
![image](https://cloud.githubusercontent.com/assets/2428993/17067514/fea41992-5019-11e6-87cd-22885fcd4b23.png)

which are both included on the `HomePageViewModel` returned to the view.

That, or there is a problem with the version of the knockout library we're using in conjunction with RTM? (this is also a guess).

A very simple fix for this is to not use knockout. We're showing a simple table of data here, so MVC is the easiest way to make that happen. After a quick refactor to use MVC/razor view to show the data, the page is working again:
![image](https://cloud.githubusercontent.com/assets/2428993/17067400/940a07cc-5019-11e6-8652-a75951905225.png)

Should I submit a PR for this by "knocking out"  :facepunch: the knockout code?

**Comment by VishalMadhvani** [comment]
Any ideas as to why this broke after the rtm update?
IIRC the organisation page also does not display data.

**Comment by mgmccarthy** [comment]
Again, my guess is something with our version of knockout and RTM? Just a gues. I'd  check to see if the org page uses knockout, and if it does, check to see if there is data coming back on the model from the query handler.

**Comment by danielepo** [comment]
The problem seams be caused is caused by the fact that, in 1.0.0, MVC uses camel case names by default as announced here:

https://github.com/aspnet/Announcements/issues/194

the easiest change would be to change:

`services.AddMvc()`
to
`services.AddMvc().AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());`

as described by the article. But I think it would be better to change the case used and follow the new MVC standard. 

These are all the views that could are probably broken because they serialize objects using the Json Helper:

Areas\Admin\Views\Event\Edit.cshtml
Areas\Admin\Views\Site\EditUser.cshtml
Areas\Admin\Views\Skill\Edit.cshtml
Areas\Admin\Views\Task\Edit.cshtml
Views\Campaign\Details.cshtml
Views\Campaign\Index.cshtml
Views\Campaign\Map.cshtml
Views\Event\_EventScripts.cshtml
Views\Home\Index.cshtml
Views\Manage\Index.cshtml
Views\Organization\Index.cshtml
Views\Organization\Organization.cshtml

I'd love to take care of it

**Comment by mgmccarthy** [comment]
@danielepo, thanks for tracking that down! 

If you could check those other views to see if they are impacted, that would be really helpful. If any of them are impacted, please open a PR with the fix to the StartUp.cs class like you mentioned above.

As far as this Issue is concerned, I already have an open PR that fixes the problem by getting rid of knockout and using MVC. Since it's such a simple page, knockout here is overkill.

**Comment by VishalMadhvani** [comment]
+1 "to change the case used and follow the new MVC standard." over reverting to pre rtm Json serialization behavior.

**Comment by danielepo** [comment]
@mgmccarthy I did the PR as you suggested because the problem was spread in every view that used knockout. Now that there is a global fix for the knockout binding problem, do you think PR https://github.com/HTBox/allReady/pull/1028 it's still necessary? I my opinion even if the Home/Index view is simple enough to don't require knockout, the use of it is still consistent with other views on the site. What do you think?

**Comment by mgmccarthy** [comment]
@danielepo 

First, thank you for you contributions. I appreciate you jumping in and doing the research for this as well as submitting a PR.

As far as deleting PR #1028, I'm probably the wrong person to ask because I believe frameworks like knockout should only be used when it's warranted. Warranted to me means there is some type of dynamic UI functionality on the page which MVC would not be good at which certain frameworks, like knockout, Angular, etc... are good at. 

A good example of this in AllReady is creating or editing Tasks. There is a part of the UI that allow you to dynamically add Required Skills to a task before creating a Task or editing an existing task:

![image](https://cloud.githubusercontent.com/assets/2428993/17401555/4dfde2e6-5a1c-11e6-8b4e-6ce41078cdf2.png)

Every time you hit "Add", you add another drop down in which you can add a Required Skill to the Task. You can also remove these items as well (my Required Skills dropdown list is empty right now, probably b/c of a specific branch i'm working on locally)
![image](https://cloud.githubusercontent.com/assets/2428993/17401610/8e53315c-5a1c-11e6-9a05-dad827ed9095.png)

Home/Index, IMO, does not warrant the usage of the overhead of knockout when we can get the job done with MVC. The TaskController views, however do warrant the usages of knockout b/c of the dynamic nature of the UI.

However, I am not a project owner, and this is open source, so I am going to defer this decision to the project owners.

@tonysurma @MisterJames @BillWagner can we get a decision on this?

**Comment by danielepo** [comment]
@mgmccarthy that's actually a good point, thank you for the explanation, the project I'm currently maintaining overuses Knockout so I couldn't understand it before. I'm also not used to this open source thing :)

**Comment by mgmccarthy** [comment]
@danielepo keep in mind my comment above is my **opinion** about using a framework that doesn't need to be used in a specific case.

We'll let the project owners weigh in on it. Looks like they have a good amount of PR's to work through and merge as well, so they have their work cut out for them :wink:
