### ISSUE TITLE
from user experience standpoint not fan of delete buttons on the far right

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1247]
From a user experience standpoint, I am not a fan of the delete button for the grids being on the far right while the rest of the action buttons are on the far left.  It feels like all of the action buttons should be together.  In fact, I didn't even notice the delete button until I had navigate through several of the grids since was expecting all actions on the left.

![image](https://cloud.githubusercontent.com/assets/708423/18652583/622b2f04-7e88-11e6-8218-e0e17f466868.png)

**Comment by stevejgordon** [comment]
@digitaldrummerj I agree it's probably better to keep them together. Personally I'd put them all in the right column since one can scan the information before worrying about any actions to perform.

We do have a wider redesign/UX/UI improvement we want to make the whole application less backend dev styled! I'd personally agree we start by putting the actions together as an initial improvement here.

Whatever we do in one place we should ensure we are consistent in other areas so that the experience is always the same and users become familiar with the layout.

**Comment by dpaquette** [comment]
All the actions should definitely be together but be sure to add some spacing between the "regular" actions and the delete actions. There is nothing more annoying than accidentally clicking or tapping on the delete button.
