### ISSUE TITLE
rename AllReadyTask to Task (low priority)

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1387]
I know `Task` is a reserved word in .NET framework, but to declare a var of `Task`, you can always use:

```
var @task
```

I use `var @event` when querying for event data.

**Comment by aastha93** [comment]
I am taking this issue .

**Comment by tonysurma** [comment]
Hello @aastha93  I wanted to check in after the event and see if there was a pull request to update this - knowing GitHub was down during the hackathon.  Thanks!

**Comment by mgmccarthy** [comment]
just to clarify, this deals with renaming the AllReadyTask model (aka ,EF-tracked entity to Task). In this folder \Web\Model\AllReadyTask.

we can use `var @task` b/c task is a reserved keyword in .NET.

**Comment by mgmccarthy** [comment]
when I tried to do this on my own, the renaming went fine, the migration went fine, I rebuilt succesfully and ran the site.

However, when looking the Index action method on the HomeController, I received this message

![image](https://cloud.githubusercontent.com/assets/2428993/21084964/0653af84-bfd9-11e6-84e5-1364b4895f26.png)

So it looks like the exception for the ambiguous reference is coming from the MVC.Rendering code in the .NET Core framework.

That being said, I'm thinking this issue should really not be worked on, unless someone wants to go in to the .NET core code and find a way to specific the `System.Threading.Tasks.Task` for whatever code implements `public Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IndexViewModel> Html { get; private set; }`

**Comment by tonysurma** [comment]
Hey @mgmccarthy didn't this get completed during the London Ontario Hackathon via @TomWalkerCodes  ? Is the error above still an error we need to worry about?

**Comment by mgmccarthy** [comment]
@tonysurma, I don't know. Either way, it's low priority. I do know that the name of a "Task" in allReady is still `AllReadyTask`.

**Comment by stevejgordon** [comment]
@tonysurma I haven't seen anything come in to change the naming. I think it's a post v1 item now and if it's going to cause pain maybe leaving as it is would be for the best.

**Comment by tonysurma** [comment]
did a little research and I think this is the one I am remembering https://github.com/HTBox/allReady/pull/1625

**Comment by stevejgordon** [comment]
@tonysurma Well remembered! Hadn't spotted that one. A quick scan and that seems to mostly rename local variables rather than the main allReadyTask model object that this was looking to address. So I think, if the AllReadyTask bothers us (it did bother me originally but I'm not too fussed now) we still need this to tackle it (with care). If we are going to do it, it would be safer pre v1 as the migration flow would be more complicated once we have live data we care about maintaining.

**Comment by naeemsarfraz** [comment]
So I've been looking at this during the codeathon at NDC and it's challenging. I won't get through it today but I'm happy to continue to look at it after today.

I would like to ask: what's the thinking behind renaming `AllReadyTask` to `Task`? It causes plenty of collisions because of `System.Threading.Tasks.Task`, which @mgmccarthy saw in the screen shot that was provided.

After a quick chat with @RichardCampbell I understand the motivation may be to debadge it from All Ready. In this case can we consider a name other than Task? Is there a name which is a little more domain specific? What does the task represent? A job the volunteer has to do? Is Job a suitable candidate?

Thoughts @stevejgordon, @tonysurma?

**Comment by mgmccarthy** [comment]
@naeemsarfraz, my thoughts are unless we name this entity to something other than `Task` (like you mentioned), we might be stuck with the `AllReadyTask` name for now.

@tonysurma @MisterJames @stevejgordon what do you guys think? not too sure if `Job` is the way to go here...

**Comment by stevejgordon** [comment]
@naeemsarfraz - A while back we had these called Activities within the domain but they where changed to tasks to align with the Red Cross language so I'd want @tonysurma's input on this really.

What this actually represents is a resourcing requirement as part of the event which can be time bounded. So essentially we're saying we need 2 ladder holders on the 20th of January. Users can then volunteer to fulfil that requirement.

Org admins use the volunteers available from tasks to build up their teams in each itinerary.

**Comment by naeemsarfraz** [comment]
How does `VolunteerTask` sound to everyone?

**Comment by stevejgordon** [comment]
@naeemsarfraz Works for me but would want input from projects owners as well

cc/ @tonysurma @MisterJames

**Comment by tonysurma** [comment]
VolunteerTask Works for me.  I would not suggest activities return.
