### ISSUE TITLE
Build out SmsResponseController

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1405]
pinging @MisterJames @tonysurma @stevejgordon for feeback on if the assumptions I'm making below are correct.

This Issue is expanding upon the following line items from Issue #1084: 
- If request is confirmed add "'N' if you can no longer make it" and if they respond N mark unassigned
- If request is not confirmed add "'Y' if you can make it, 'N' if you can't" and set status as above

allReady sends sms confirmation messages to requestors whose Request has been Assigned to an Itinerary. The following code sends these messages:

```
RequestsAssignedToIntineraryHandler
SendRequestConfirmationMessagesAWeekBeforeAnItineraryDate
SendRequestConfirmationMessagesADayBeforeAnItineraryDate
SendRequestConfirmationMessagesTheDayOfAnItineraryDate
```

The requestor can reply "Y" or "N" to confirm the request. This Issue includes the following work:
- identify how to attach the RequestId from the Request model to the outgoing sms messages. The RequestId has to survive the round trip of being sent out (by the classes listed above) and then trip back to SmsRequestController.
- in SmsRequestController, we look up the Request by RequestId. We **cannot** correlate the incoming request  from the Requestor by PhoneNumber as the Requestor could have more than multiple requests that have been added to different Itineraries. If we looked up the requestor by phone number, we would end up with two requests, so we would not know which request to mark as Confirmed.
- there is code already written in SmsRequestController that needs to be uncommented based on the Requestor's reply of "Y"/"N"
- most likely, this will involve Twilio to a greater extent than how we currently use it (which is just to send sms messages). You will need to set up a Twilio account and either use your mobile phone or open a Google Voice account to test the receiving of text messages as well as the reply of "Y"/"N" to those text messages.

**Comment by tonysurma** [comment]
Those assumptions look correct to me

**Comment by mgmccarthy** [comment]
whoever picks this up, please ping me first to answer any questions you may have

**Comment by mgmccarthy** [comment]
@tonysurma this might need to be updated to P1. If we're sending out sms confirmation messages to requests we receive via the getasmokealarm portal, the requestor's will be unable to reply to our text message to confirm or cancel the request.

**Comment by EmilyLuijbregts** [comment]
@tonysurma -shall i update the label to P1? or is it OK to leave as P2?

**Comment by stevejgordon** [comment]
@mgmccarthy - I've been doing a quick bit of reading and think I can see how we do this. I've setup a free/trial account so I can test this locally. Happy to chat on it with you as well.

**Comment by stevejgordon** [comment]
Setting up a Twilio number which can accept a Y/N response and send this onto a handler in our system seems reasonably straightforward. You can have a single handler (endpoint URL) defined for a number so we have to determine how we architect things. I would think using a single number is preferred but this also means we have a single endpoint to handle responses. This can be managed but requires a flow roughly as follows...

- Send SMS notification to the request phone number (to do - decide if we can validate that a number is a mobile/cell number which can accept SMS)
- Record the notification type, date and request into a "notifications" table
- Requester receives an SMS and replies Y or N - Sent to Twilio number for allReady
- Twilio receives the reply and sends the number and body onto our endpoint
- We lookup the most recent notification that was sent to that number, and update the request accordingly

Issues to consider...

1. In the above flow, we always have to assume the response is to the last notification we sent as the endpoint will not be able to determine for which type of message (initial assignment, 7 days before, 1 day before etc) then response is for. I believe to handle each separately we would need a unique number (extra cost) so we can have a unique endpoint for each message. That feels like overkill here but does depend on how the system needs to operate. It feels like taking the last value is probably okay in our case.

2. It's possible currently to have multiple requests with the same phone number. This will confuse the handling of responses and notifications as to update a request we have to be able to uniquely identify the request using the SMS "from" number. We could therefore enforce a rule to ensure phone numbers are unique, but what happens if someone wants to register a request for two campaigns (maybe even different orgs). i.e...

We have a Red Cross smoke alarm campaign and an unrelated Org XYZ free gas safety check campaign. A member of the public wants to sign up for each (perhaps months/years apart) but will do so using the same phone number. In this case if we allow a reused phone number, when we receive an SMS we don't know for which campaign/event it's intended. I haven't yet seen a way to set any SMS body in the reply besides what the user types. A solution to this might be unique Twilio numbers per event, or perhaps campaign, but that in itself adds cost and management requirements.

cc/ @MisterJames also for input since decisions here are quite crucial to the system.

**Comment by stevejgordon** [comment]
I believe in any case, having a table to record the notifications we have sent is going to be required, so I'll break out an issue to add that as the first part of implementing this.

**Comment by mgmccarthy** [comment]
@stevejgordon 

> I believe in any case, having a table to record the notifications we have sent is going to be required, so I'll break out an issue to add that as the first part of implementing this.

this can easily be accomplished by publishing a notification when the confirmation messages are sent and recording the pertinent information in a table.

**Comment by mgmccarthy** [comment]
@stevejgordon, my feedback on your [comment a couple comments above this one](https://github.com/HTBox/allReady/issues/1405#issuecomment-267820299):

> - We lookup the most recent notification that was sent to that number, and update the request accordingly)

Good catch about **the most recent notification**. I thought the only problem we faced was not being able to determine which request for a given mobile number we could look up.

When we record the notification was sent, we can do that in the following classes (all of which are Hangfire jobs except for InitialRequestConfirmationsSentHandler):
- InitialRequestConfirmationsSentHandler
- SendRequestConfirmationMessagesSevenDaysBeforeAnItineraryDate
- SendRequestConfirmationMessagesADayBeforeAnItineraryDate
- SendRequestConfirmationMessagesTheDayOfAnItineraryDate

this should give you the most recent notification, **with the caveat with the Hangfire jobs, b/c they're async, there is no guarantee in order of "delivery"**

an example of this is one of the jobs could fail... another one could succeed, when the retried one does succeed, then our system thinks that's the most recent notification, when in reality, it's not. **But the changes of this are low so we should not have to worry about it.**

> It feels like taking the last value is probably okay in our case.

I agree with this approach

> It's possible currently to have multiple requests with the same phone number. 

and this is what makes this a hard problem to solve, but the "most recent request" approach is going to solve it. Thanks.

> We could therefore enforce a rule to ensure phone numbers are unique, 

I agree, we should not/can't really do this. We never know what type of integration we'll be dealing with so the rules for this can change depending on integrations vs. how we handle requests internally via our UI. There is no rule anywhere stating a single phone number cannot be tied to multiple requests... especially is that same phone number's requests ends up mapped to two different Events (which could happen)

**Comment by mgmccarthy** [comment]
@stevejgordon, I was thinking a bit more about the most recent notifications table approach to solving the problem of not being able to put a unique requestid/identifier somehow in the sms text that is sent by us to requestor's, then back again to allready. All we have to go on, as you've pointed out, is a phone number, which is not enough.

The other problem with the notifications table is we're making the assumption that the requestor is responding to our sms confirmation message(s) in the order that they've received (aka, the order we send them to the requestor).

Although, most of the time, I believe that users would respond in the correct order, it's possible that they would not (when receiving sms texts for to confirm two different requests), and hence, when making the assumption that the text they're sending us is the most recent we sent them, could end up confirming the wrong request.

Do you know of any way to put something in the HTTP headers (like the RequestId) or something else that could survive the round trip of us sending them the sms confirmation, and the requestor sending us back confirm/cancel? It seems like something... "easy"... I just don't know enough about SMS/Twilio to know how that technology really works.

Being able to work with a unique id w/out making assumptions would be the best way to go here.

Thanks

**Comment by tonysurma** [comment]
> Do you know of any way to put something in the HTTP headers (like the RequestId) or something else that could survive the round trip of us sending them the sms confirmation, and the requestor sending us back confirm/cancel? It seems like something... "easy"... I just don't know enough about SMS/Twilio to know how that technology really works.

I know that there isn't such a thing and technical no relationship between the SMS out and back to you in Twilio, so you have to match up by phone number you were texting for example

**Comment by stevejgordon** [comment]
@mgmccarthy @tonysurma - Yep it's a tricky problem for sure. As Tony says, there seems to be no obvious way to tie a response back to the message we sent. You can get a SID for messages you send, but it doesn't seem to return it on the reply.

If we want to use a single Twilio number (for all of the messages) then we will have to update based on purely working back to the request that had the most recent notification against the sender's number. So we take a N reply as a rejection for any level of message and a Y as accept. It's not super clean.

@tonysurma - Do we want to work that for now and see how it goes? Or do we need to investigate further? We could use a unique number per message type but that means paying for 4 Twilio numbers at the moment.

We could send a URL in the message to confirm instead, but that only works for recipients with a data plan which we can't rely on.

I've started work on the notifications table structure (under issue #1647) and will hook into the notification sending points as necessary since recording that data will probably be useful.

**Comment by tonysurma** [comment]
Do that for now as you said.

**Comment by mgmccarthy** [comment]
@stevejgordon @tonysurma 

> You can get a SID for messages you send, but it doesn't seem to return it on the reply.

that. sucks. what's the point of generating a unique id for a message unless it can be tied back to the sending service?

**Comment by tonysurma** [comment]
It's a limitation of SMS, there is no concept beyond a single message in it, no concept of reply or conversation.  It's simplicity/limitations is the root of it's power and ubiquity

**Comment by stevejgordon** [comment]
Added a new issue to get this finalised with support for ensuring we have valid phone numbers in the system when requests are created. I believe we will then be in reasonable shape for v1 and initial deployments.

**Comment by stevejgordon** [comment]
@tonysurma If you agree I think we can close this issue with the v1 functionality we have now included?

**Comment by mgmccarthy** [comment]
@stevejgordon I agree.

**Comment by tonysurma** [comment]
Agree
