### ISSUE TITLE
Implement skipped tests in ClosestLocationsQueryHandlerShould

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1436]
@tonysurma please label with jump-in

**Comment by HamidMosalla** [comment]
@mgmccarthy I don't think there is any way we can test `HandleInvokesGetClosestLocationsWithCorrectData` without some way to mock the `FromSql`, since it is a static method, we need a wrapper of some sort, I'm not sure though, I went ahead and [asked a question](http://stackoverflow.com/q/40726638/1650277) on StackOverflow about it just to make sure, if you know of any way, please let me know.

**Comment by Pvlerick** [comment]
@HamidMosalla I posted an tentative answer for you: http://stackoverflow.com/questions/40726638/mocking-fromsql-in-entity-framework-core/42502650#42502650

However, looking at the code, I don't think testing this has a high added value: simply testing that parameters end up in a SQL statement is kind of useless since there is no logic, unless other layers (interceptions with DI?) might modify these.

**Comment by mgmccarthy** [comment]
@HamidMosalla, @Pvlerick is correct. There is no value in testing this. There was another unit test for a class that had the same issue (it's encapsulating a store proc call)

after disciussions with @dpaquette, we decided that we do not need to test this code, and there is no value add.

Please read Issue #1542 for the details.

Thanks

**Comment by BillWagner** [comment]
closing per earlier discussions.
