### ISSUE TITLE
Clarification on the usage of CQS principle in the code base

### ISSUE THREAD

**Issue by HamidMosalla** [HTBox/allReady#1557]
Most of what I know about CQS comes form Mark Seemann's blog, which basically says that when we run a query we don't mutate any states in the system and we just return the result and asking the question shouldn't change the answer, conversely when we execute a command we mutate states in the system and we don't return anything.

He argues that this makes our code clear and easier to reason about, and if we needed a value for example recently created entity's `id`, we make another query for that, or [we generate it ourselves](http://blog.ploeh.dk/2014/08/11/cqs-versus-server-generated-ids/) as opposed to auto-generated database ids.

My question is, are you agree with my understanding of CQS? if yes, I saw some command handlers in the project return an id, for example `EditCampaignCommandHandler` returns an `id` and use it in the `CampaignController`:

```
public async Task<IActionResult> Edit(CampaignSummaryViewModel campaign, IFormFile fileUpload)
{
...
    var id = await _mediator.SendAsync(new EditCampaignCommand { Campaign = campaign });    
    return RedirectToAction(nameof(Details), new { area = "Admin", id }); 
....
}
```
When in fact we already have the id (`campaign.Id` from action's parameter) to return, I wanted to know is there any guideline on the use of CQS in this project? or you think this kind of adherence to CQS is too severe and doesn't provide any real value? Thanks.

**Comment by mgmccarthy** [comment]
@HamidMosalla, in this specific case you mentioned, if we already have the id in the controller before we dispatch the command, we should use that id and not return anything from the command handler (and like you said, in a "perfect" world of CQS, command handlers do not return anything).

The problem with your example above as it applies to AllReady is a lot of our `Edit` command handlers are really handlers that .AddOrUpdate... if the entity does not exist, create it, if it does exist update it. 

In the case of the creating the entity, we do need to return the id to the caller, b/c the caller is in a `POST` action method and following the principle of PRG, we want to take that new id, and redirect the user to a GET action method next.

That being said, what's really keeping us from following a true CQS or CQRS pattern here is the inability to allow calling code (aka, "the client) to generated ids instead of the database.

A simple example is if we changed to using all GUID's for our primary key values for all EF-controller entities. 

Because this change is probably not going to happen this late in the game, then we'll have to accept the slight deviations we're taking when applying CQS/CQRS to our codebase.

What I need to do is write up a quick CQRS guideline in our [developer guidelines](http://htbox.github.io/). I'm going to open an Issue and have @tonysurma assign it to me so I can get this done.

Thanks for pointing this out.

**Comment by HamidMosalla** [comment]
@mgmccarthy One other thing to add here is that since we use an object for every command or query, from the pragmatic point of view, we will get what we could ideally get form CQS, we know what is command and what is query, and in the case of returning `id`, that doesn't really mutate any state, but if we're doing something outside MediatR query and command objects, it is a good idea to adhere to the CQS more strictly.

**Comment by EmilyLuijbregts** [comment]
Issue #1558 created to track this issue
