### ISSUE TITLE
Adding unit tests for GoogleOptimizeRouteService

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1579]
We need to test the expected flows through this service

**Comment by forestcheng** [comment]
I am taking this issue.

**Comment by tonysurma** [comment]
thanks @forestcheng

**Comment by forestcheng** [comment]
I finished it in the meetup of Humanitarian Toolbox Hackathon in London, ON. It's my first time to write such kind of Unit test. I opened a pull request under the branch of TomWalkerCodes : https://github.com/TomWalkerCodes/allReady/pulls
You're welcome to review the code and give me some comments and suggestions. I hope to do more related work.

**Comment by tonysurma** [comment]
cc @mgmccarthy 
@forestcheng @TomWalkerCodes thanks for taking this on.  @TomWalkerCodes how do we reference this and/or is it ready for a PR to review for our repository?  thanks

**Comment by chinwobble** [comment]
@forestcheng I noticed the unit test you wrote still makes a network call. The current design for GoogleOptimizeRouteService does not appear to allow responses to be mocked. 
@tonysurma  Is this a concern?

**Comment by mgmccarthy** [comment]
@forestcheng @chinwobble @TomWalkerCodes @tonysurma @stevegordon

None of our unit tests should be making real calls to any type of service, especially http based services. 

That type of test is an integration test, not a unit test. 

I won't be able to look at anything until after the holidays, but are we lacking the appropriate abstraction in order to make the class testable?

**Comment by chinwobble** [comment]
@mgmccarthy I believe we are missing properly abstractions. At the moment the GoogleOptimizeRouteService uses a static instance httpClient inside the class. Similarly, the azure related services such as IImageService appears to create BlobContainers inside the class and therefore cannot be unit tested.

**Comment by mgmccarthy** [comment]
I would not worry about testing classes that use IImageService right now. Purely based on memory,there is not too much going on in those classes that is not tied directly to setting up the config and establishing a connection to the real blob service. The reason IImageService exists in the first place is to allow testing of classes that need that service. 

HttpClient is scoped as singleton on purpose (Google it to see why). When I get back from the holidays, let me see if there is a way to abstract it (if we need to). Any class that works with HttpClient should only do work associates with setting up conf, connecting, then doing work with the call (GET, POST)

**Comment by mgmccarthy** [comment]
@forestcheng @chinwobble  @stevegordon

cc @tonysurma

in order to unit test GoogleOptimizeRouteService, we need a way to mock HttpClient. The reason is we're making an HttpClient call, then based on the return from that call, doing work:
```
var response = await _httpClient.GetAsync(GenerateGoogleAPIUrl(criteria));

if (response.IsSuccessStatusCode)
{
    var content = await response.Content.ReadAsStringAsync();
    var result = JsonConvert.DeserializeObject<GoogleDirectionsResponse>(content);

    if (result.Status == GoogleDirectionsResponse.OkStatus)
    {
        requestIds.AddRange(result.Routes.SelectMany(r => r.WaypointOrder).Select(waypointIndex => criteria.Waypoints[waypointIndex].RequestId));

        return new OptimizeRouteResult { RequestIds = requestIds, Distance = result.TotalDistance, Duration = result.TotalDuration };
    }
}
```

off the top of my head, there are two approaches we can take:

1. call `var response = await _httpClient.GetAsync(GenerateGoogleAPIUrl(criteria));`, then dispatch a message to another handler that will act on the response data and do the work. That way, we separate the class the invokes the HttpClient call from the class that makes a decision based off the data that is returned. I like this approach as it adheres to SRP and makes unit testing easier

2. introduce the concept of an IHttpClientFactory, which will allow us to get a reference to a static HttpClient using an abstraction. We'd need to write up the abstraction, and instead of injecting HttpClient into GoogleOptimizeRouteService, we'd inject IHttpClientFactory... the code could look something like this:

```
//the GetStaticHttpClient method will return an HttpClient that is scoped as a singleton so we can re-use the connection
var httpClient = httpClientFactory.GetStaticHttpClient();
var response = await httpClient.GetAsync(GenerateGoogleAPIUrl(criteria));
```

If we needed to hang onto multiple singlton scoped instances of HttpClient, we could add a "key" string to the GetStaticHttpClient() call that would look for that "named" HttpClient and return it, and if it didn't exist, create it.

Again, the first option seems simpler b/c we do not have to introduce and abstraction layer that is only needed for unit testing.

**Comment by stevejgordon** [comment]
@mgmccarthy - A while back I had a similar issue and ended up with a IHttpClientWrapper exposing the Send/GetAsync methods. I could then moq that for testing. I then had a couple of implementations of this, holding a static HttpClient each (that was for a requirement that was better met using different clients). This is essentially a slight variant on the factory idea.

You can also construct a HttpClient passing in a HttpMessageHandler which you can Mock more easily. I tried that also but moved away from it in the end. It worked but seemed a little confusing.

I'm a little worried about how many "layers" of handlers we end up with as it does make following the code a little harder, but does adhere closer to SRP. I guess it's a balance between SRP and testing vs readability and ease of contributing. 

In this case the handler's responsibility is to optimise the route and in doing so calling the API and handling the response feels okay to me.

Personally I fall more in favour of a wrapper/factory we can more easily mock.

**Comment by mgmccarthy** [comment]
@stevejgordon I just searched the AllReady project for `IHttpClientWrapper` and didn't find anything. Was it something you did for this project or something you did at work?

I'm fine with either solution. Thanks

**Comment by stevejgordon** [comment]
@mgmccarthy - It was a work thing :-)

**Comment by mgmccarthy** [comment]
let me play around with some code and I'll see what I come up with. Thanks for the input and feedback.

**Comment by mgmccarthy** [comment]
@stevejgordon, this is what I came up with:

`IHttpClient` and `StaticHttpClient`:
```
public interface IHttpClient
{
    Task<HttpResponseMessage> GetAsync(string requestUri);
}

public class StaticHttpClient : IHttpClient
{
    private static readonly HttpClient HttpClient = new HttpClient();

    public async Task<HttpResponseMessage> GetAsync(string requestUri)
    {
        return await HttpClient.GetAsync(requestUri);
    }
}
```

in Startup.cs:
```
services.AddSingleton<IHttpClient, StaticHttpClient>();
```

This is a bare-bones implementation and it a good place to start, but will not scale well for code that needs a static HttpClient instance for a POST that needs to add security tokens to its http headers ([SendRequestStatusToGetASmokeAlarm](https://github.com/HTBox/allReady/blob/2294321467324a2c737f2819f8cc65355b8658b0/AllReadyApp/Web-App/AllReady/Hangfire/Jobs/SendRequestStatusToGetASmokeAlarm.cs))

We would either need to add more to the IHttpClient API and/or have different ways to set/clear headers on the static instance of the HttpClient.

However, this introduces the problem of a single HttpClient static instance being used for everything, where if we add a header for a POST operation, then another operation uses the static instance for a GET, we could end up introduction failures, or vice-versa, a GET op clears the headers, then a POST op fails.

That's why I initially was thinking an HttpClientFactory would be a good idea. We could add a method per HttpClient specific usage for scenarios where using an existing HttpClient would not work. In the case of usage between `GoogleOptimizeRouteService` and `SendRequestStatusToGetASmokeAlarm`, the http client factory api could look something like this.

```
public interface IHttpClientFactory
{
    HttpClient GetGoogleOptimizeRouteServiceHttpClient();
    HttpClient GetSendRequestStatusToGetASmokeAlarmHttpCliennt();
    ...and/or...
    HttpClient GetHttpClientForGetOps()
    HttpClient GetHttpClientForPostOps(List<HttpRequestHeaders> httpRequestHeaders)
}
```
 using the factory, we could support either usage specific scenarios (this HttpClient should be used for GET's, this one used for POST's that need to add http header info, etc...) and/or business specific sceanrios (like the names of the two methods in IHttpClientFactory above).

Just some thoughts on eventually how to manage what I'm sure will be multiple static HttpClient's being used across different parts of the system.

I'd be interested to know your thoughts on this approach.

In the meantime, to get OptimizeRouteCommandHandler testable, I can easily add the interface I talked above at the very top of this post into the class, then let @forestcheng take a crack an the unit tests.

Thoughts?

**Comment by mgmccarthy** [comment]
cc @stevejgordon 

@forestcheng and @chinwobble, now that PR #1682 is merged (aka, we have a testable IHttpClient), can either one of you take another shot at writing unit tests for GoogleOptimizeRouteService?

Thanks

**Comment by forestcheng** [comment]
I'm sorry that I'm still a beginner of ASP.NET and I have many things to learn. Could @chinwobble or someone help writing the unit test so that I can learn from you?

Thanks a lot.

**Comment by chinwobble** [comment]
@mgmccarthy, sure I can write the unit tests for this service class. 
Please asssign to me.

**Comment by chinwobble** [comment]
@forestcheng I've starting writing the unit tests here 
https://github.com/chinwobble/allReady/commit/5fc62e847c9ba2166842046bb83834af5770c4f5
Perhaps you could help write the others to learn. Let me know if anything is unclear.

**Comment by chinwobble** [comment]
@mgmccarthy  as others have identified, when the GoogleOptimizeRouteService fails, nothing is logged or reported to users. Should making updates such as introducing more logging be a separate PR from the PR for the unit tests?

**Comment by mgmccarthy** [comment]
@chinwobble, don't worry about logging for now. If GoogleOptimizeRouteService fails, it will throw an exception (which is fine, b/c that service failing is exceptional) and the user will be shown our generic 404 message.

In the future, we will be using Polly to execute retry policies for outgoing web service calls like this one, but that's not part of the v1 deliverable.

Also, we don't really have any type of logging policy set up in the live environment yet, so until we figure that out, introducing any type of logging code doesn't make sense.

For now, we just need the unit test coverage for `GoogleOptimizeRouteService`.

Thanks
