### ISSUE TITLE
Login via Twitter Fails

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1763]
After an initial successful login via twitter if you logout and then try logging in the next time we get an application error.

AllReady.Features.Login.ApplicationUserQueryHandler+<Handle>d__2.MoveNext() in ApplicationUserQueryHandler.cs
            var normalizedUserName = message.UserName.ToUpperInvariant();
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
AllReady.Controllers.AccountController+<ExternalLoginCallback>d__20.MoveNext() in AccountController.cs
                var user = await _mediator.SendAsync(new ApplicationUserQuery { UserName = externalUserInformation.Email });

**Comment by shahiddev** [comment]
@stevejgordon  Happy to pick this up tomorrow if you have other issues to deal with? I presume the twitter account being used to register the app has requested email permissions from Twitter?

**Comment by tonysurma** [comment]
Including @mgmmccarthy

**Comment by tonysurma** [comment]
And @mgmccarthy :)

**Comment by stevejgordon** [comment]
@shahiddev - Sure, please do. I will be unlikely to get to it until later today at the earliest.

We don't currently get the email back from Twitter. I believe @mgmccarthy has tried a few permissions and even on our API call to get the user info it's not available in the returned data.

That certainly is the issue, since upon login it's expecting to have the email in order to match up the login to an existing user in our system. The email is null and blows. I have some thoughts if we can't get the email as we could use the providerId (twitter ID) to look up the user in the db directly in the case of Twitter. But if you have thoughts on getting the email then that would be an easier option.

**Comment by mgmccarthy** [comment]
@shahiddev cc @tonysurma @stevejgordon 

[I wrote a blog post about my experiences trying to pull email from Twitter](http://www.michaelgmccarthy.com/2016/07/07/asp-net-core-retrieving-a-users-email-and-name-from-the-twitter-external-login-provider/). The nitty-gritty of what I had to go through is in that blog post.

The code at for the Twitter provider at the point used LinqToTwitter to make a call that allowed me (with the  correct Twitter configuration) to pull email. We had to remove LinqToTwitter b/c it is incompatible with the version of the asp.net core framework/version we're on now and replace it with manually constructed http calls to Twitter's API.

Since LinqToTwitter was doing "magic" in invoking the Twitter API that I did not have first hand knowledge of, I'm not too sure of the answer to this problem, but if you wanted to pick this up to investigate it, I can try to answer any questions you might have.

[Also check this blog post](http://www.bigbrainintelligence.com/Post/get-users-email-address-from-twitter-oauth-ap) that talks about the additional http request to a different endpoint to retrieve the user's email address.

In the end though, we might not want to do this, b/c it seems that when asking for this extra info (or at least when the LinqToTwitter code did it), we ended up with a very "greedy" Twitter provider that asked the user logging in for the AllReady application to have a LOT of control over their Twitter account, the type of control that no sane person would grant an application:
<img width="971" alt="screen shot 2016-10-06 at 21 17 43" src="https://cloud.githubusercontent.com/assets/785891/19169026/81975d9c-8c0a-11e6-842e-431a98529459.png">

(check Issue #1358 for more details)

**Comment by shahiddev** [comment]
Thanks for the info @mgmccarthy  
Just investigating at the moment, initial thoughts are its not directly related to the Twitter API because the user is required to complete the additional information when registering. It looks like that additional information isn't being retrieved correctly. Will dig further...

**Comment by mgmccarthy** [comment]
@shahiddev, thanks for taking a look. Do you mind if we assign this issue to you?

@tonysurma @stevejgordon can either of you add @shahiddev to the project so we can assign this issue to him?

**Comment by stevejgordon** [comment]
@shahiddev - You should have an invite waiting which will then allow me to assign to you directly.

The issue is that on login we still hit the ExternalLoginCallback which expects to be able to check for the existing user by email, retrieved from the externalUserInformationProvider. As this returns no email for Twitter the lockup failed and we have a null user.

When I looked quickly last night I was think we'd be able to query the DB directly using the twitter provider id (twitter only) and we could then find the related application user from that. In my head it works! :smile:

**Comment by shahiddev** [comment]
I've accepted now so please assign.

@stevejgordon yes that's the gist of it, basically we need to be able to retrieve the registered user based on the information that twitter has given us (which is very little!).

**Comment by mgmccarthy** [comment]
I'd just like to say one more time how much Twitter sucks. rant over.

**Comment by shahiddev** [comment]
I guess the only other thing to bear in mind on this is that we potentially want to go down the route of identifyserver  then AllReady will no long contain any of the authentication code instead relying on OpenIdConnect/OAuth2 middleware. 

I we intend to go to V1 with the current authentication approach then its worth fixing, otherwise it may be better to focus energy on relying externalising the authentication instead?

**Comment by shahiddev** [comment]
@stevejgordon (I tried to accept the invitation - not sure if it worked?)

**Comment by stevejgordon** [comment]
@shahiddev - Looks good. You're now assigned.

I think realistically if the go live is end of the month then having IdentityServer fully thought out and implemented will be unlikely for v1. If we can do the minimum required to tweak the flow here I think it will be worth doing so that the first use can take place.

**Comment by shahiddev** [comment]
@stevejgordon - thanks, yes understood and agreed.

Ok I think I've got this working in principle with minimal code changes, infact probably can remove a chunk of code (my favourite thing!).

To retrieve the email address now from Twitter is simpler than it would appear to have been before. You have to just tick the request email address option and it appears to be enabled automatically, no more manual intervention from Twitter. 

With regards to the concerns about the greedy profile, this is the consent screen I'm seeing when I configure the app registration to request email but otherwise read only profile (appears to be the minimal information you can request).
![image](https://cloud.githubusercontent.com/assets/11890711/22261439/dd64e3be-e264-11e6-874f-3e75e176ce2c.png)

 I think that looks acceptable compared to the version posted by @mgmccarthy ?

this is the configuration required 
![image](https://cloud.githubusercontent.com/assets/11890711/22261644/9cec0ea6-e265-11e6-822d-b2b92cbac771.png)

**Comment by mgmccarthy** [comment]
@shahiddev this is definitely the non-greedy profile. Most people would agree to this. Nice work!

**Comment by shahiddev** [comment]
There is an edge case where we may not be able to retrieve the user email address, this may occur for 1 of 2 reasons
1. We've not configured the Twitter application to request email address
2. User does not have an email address configured or it is unverified

If we are unable to retrieve the email address its not possible to determine who the user is (we don't persist any twitter id or related info in order to try and link the user back to an existing account). 
My PR will log this error but its not able to handle this further. 

reason 1 is a deployment/setup thing which shouldn't happen once its setup correctly.
reason 2. Could potentially happen - if this is the case at the moment there is nothing to handle this. It will still crash, I'm not sure what the best approach is here, redirect to a 404 page or just back to the login page?  

Given the fact that currently the twitter login doesn't work, with this "fix" we have the 90% case covered (i.e. user has twitter email and we can retrieve it ok). 
I think we could ensure this 10% edge case is covered off with the IdentityServer solution? 

Any thoughts?
cc @stevejgordon @mgmccarthy

**Comment by stevejgordon** [comment]
@shahiddev - I'm all for getting the majority of cases sorted first as it will facilitate the testing.

However I think I see a way we can cope with the 10% case also. On the ExternalLoginCallback we get a providerKey along with the name of the provider. Within allReady there is a IdentityUserLogin table from ASP.NET Core identity. That should store the registered provider(s) for a user.

So I think with a slight tweak to our context we can make this accessible via EF and write our own query for Twitter to get the UserId from the ProviderKey and then we can query back for the UserEmail using the UserId to be able to tie the login to an actual user.

**Comment by shahiddev** [comment]
@stevejgordon I was looking at the ApplicationUser table which is general Identity fields and therefore was reluctant to modify this to deal with Twitter specifically but the table you mention does work so yes. 
I'll open a new issue to cater for this edge case so we can get the rest of the fix reviewed.
Thanks

**Comment by mgmccarthy** [comment]
@stevejgordon as long as we're sure exposing `IdentityUserLogin` table to EF context is a good idea. It will fix the two edge cases @shahiddev found, but I want to make sure we're not accidentally opening this table up to query against/write to when it's really a "framework-owned" table.
