### ISSUE TITLE
Add httpClient abstractions SendRequestStatusToGetASmokeAlarm

### ISSUE THREAD

**Issue by chinwobble** [HTBox/allReady#1769]
At the moment we are missing proper abstractions `SendRequestStatusToGetASmokeAlarm` class.

**Comment by mgmccarthy** [comment]
@chinwobble, the problem with using the IHttpClient abstraction on this one (and why I haven't moved to it yet) is b/c of the http headers involved in putting the auth token onto the POST request. At least that was my reasoning when I wrote it.

I just did a quick search around and it looks like TwitterService uses the IHttpClient static instance in a POST scenario. Instead of attaching the http headers to the client, it builds an HttpRequestMessage and attaches the headers to the request, then sends the request via HttpClient. In other words, HttpClient stays "header agnostic", which it should as it's a static instance, it will be used for both GET and POST scenarios and we would not want to attach headers to the client for an instance where it's being used in the wrong call.

If you'd like to have a go at changing SendRequestStatusToGetASmokeAlarm to utlizie the static IHttpClient like TwitterService does, please do and let me know how it goes.

**Comment by mjmilan** [comment]
Forgive me if this is already taken care of architecturally, but that sounds like a very campaign specific method name to me.

Should we be placing such campaign specific code in the application, and if so, should we be treating it as a campaign specific add-in?

I would check, but I am using a mobile phone at the moment...

**Comment by mgmccarthy** [comment]
@mjmilan  cc @stevejgordon @tonysurma 

Yes, it is campaign specific, but until we examine some real world usage, and b/c the launch of v1 is presumably going to happen this month, we had to create the first delivery accepting some Red Cross/GetASmokeAlarm-specific code/verbiage.

As we better understand usage of the system, we'll be able to start to generisize some of this functionality, but make no mistake, there is no 100% generic solution that can handle any and all requirements any and all integrations, and trying to build something like that for the first release of the software would be a mistake.

Keep in mind this is integration code (not business code), and since each integration is different, it requires different code in order to process incoming data to our model (incoming integration), or outgoing to to the integration's model (outgoing integration).

**Comment by chinwobble** [comment]
Could someone please assign this to me?

**Comment by mgmccarthy** [comment]
@chinwobble, assign what? I need feedback from project owners first as to when we're officially launching v1 so we don't start to refactor/change code to something more generic. We first need to figure out what that actually means.

cc @tonysurma @MisterJames

**Comment by chinwobble** [comment]
I think this can be closed now that #1776 has been merged.
