### ISSUE TITLE
Improve Non-Windows Installation Instructions

### ISSUE THREAD

**Issue by jrw348** [HTBox/allReady#1815]
As new contributors to the project, Ryan Young and I (Justin Weaver) ran into some issues trying to install allReady for development on our non-Windows dev environments. We noticed that: 

- The existing documentation for installing in linux had some gaps that required searching through the guides for the other platforms
- The existing documentation for installing in mac OS X could not be followed. 

Both Ryan and I were able to get the project installed and working after piecing together information scattered throughout the wiki and we would like to use our experience to improve the existing documentation.

**Comment by jrw348** [comment]
The platform on which I develop is Mac OS X. If possible, I would like to be assigned to this issue to help revise the dev env setup instructions for that platform.

**Comment by RyanYoung25** [comment]
I was able to install it on Ubuntu 16.04 and would like to help revise the instructions for it. I would also like to be assigned to the issue.

**Comment by RyanYoung25** [comment]
Justin (jrw348) and I have updated the developer setup and installation instructions for both Mac OS X Sierra and Ubuntu 16.04. We have placed the instructions on separate wiki pages (one per OS) and updated the developer's setup wiki page to point to them. See these links:

[Developer Setup Wiki](https://github.com/HTBox/allReady/wiki/Developer-Setup)

[Running on Linux Wiki](https://github.com/HTBox/allReady/wiki/Running-on-Linux)

[Running on Mac OS X Wiki](https://github.com/HTBox/allReady/wiki/Running-on-Mac-OS-X)

Unless there is anything else you would like us to do, we consider this issue completed. If you have any questions or updates that are necessary please let us know by posting on this issue otherwise please close the issue. Thanks!

**Comment by EmilyLuijbregts** [comment]
Thanks very much Ryan! This is great work!
@stevejgordon - who normally does documentation reviews? Can you assign this to them?

**Comment by tonysurma** [comment]
@EmilyLuijbregts actually I got a chance to review these last night and they are outstanding!  Thank you @RyanYoung25 and @jrw348 .  I didn't physically run through every step but they are very thorough and the Mac OS ones match what I have done to get that setup.
