### ISSUE TITLE
Message Newly Assigned Team Lead

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1820]
Follows on after #1813 is implemented

When a volunteer is assigned as a team lead we should send them an email and/or SMS to notify them of their assignment as lead.

We should include a link to the itinerary details page for the itinerary for which they have been assigned.

**Comment by chinwobble** [comment]
@stevejgordon  I would like to work on this.

**Comment by stevejgordon** [comment]
@chinwobble Did you manage to progress on this at all?

**Comment by chinwobble** [comment]
@stevejgordon I have not begun this. Could you please assign this to me and I'll start it as soon as I can.

**Comment by stevejgordon** [comment]
Have sent you an invite to become a collaborator so that we can assign you directly. For now, assigning myself to hold this on your behalf.

**Comment by darrylsk** [comment]
Is anyone working on issue 1820 right now?  I think I am close to a candidate solution and would like to submit it for review.  Going by the CampaignManagerInvited and AddTeamMember commands as examples, I created new classes ItineraryTeamLeadAssigned and ItineraryTeamLeadAssignedHandler under the Notifications folder and added the line _mediator.PublishAsync(new ItineraryTeamLeadAssigned); to SetTeamLeadCommandHandler.  I used the existing NotifyVolunteersCommand command to send and Email and SMS message to the new Team Lead.  I added some user data to the In-Memory context, wrote a single unit test, and also tested in the browser.  Both tests have passed.  Since there hasn't been any activity on this item for a while, I'm presuming the assignee has either moved on or doesn't have free time to complete it right now, and presumably could choose another item later on.  I expect some changes will be necessary, but a quick review would be helpful guidance at this point.  Any objection to me submitting a pull request on this?
