### ISSUE TITLE
Send ManagementInvite Email to Invitee

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1889]
Breakout from #1804

We should add a notification (Mediatr) and handler to support adding an email message onto the queue when an invite is sent. This should send the invitee the email, with a link to accept the invite. We should perhaps include an optional link to decline the invite?

We should also include details of where to register if they do not have an account already.

**Comment by mk0sojo** [comment]
I can have a look at this one

**Comment by mk0sojo** [comment]
@stevejgordon 

Is it worth trying to use something like cerbeus (https://tedgoas.github.io/Cerberus/) to create HTML formatted emails or should I stick to plain text? It looks like the other emails we send are mainly plain text (possibly a hyperlink or two), but if we want an accept button, decline button and a register link it may get a bit confusing using just plain text?

Also noticed the SendGrid C# library we use is a pre release version. A more final version seems to be available (https://github.com/sendgrid/sendgrid-csharp) (uses an API key instead of user name and password and some other useful things). Is it worth upgrading?

**Comment by stevejgordon** [comment]
Hi @mk0sojo - Sorry for the delay. Have been away on holiday.

I'd suggest we start with plain text / same as current initially to get the functionality in. We have an older issue #186 which looks to include the concept of templates / more advanced email content.

As for SendGrid - might be a good idea to update. I'll open an issue to review and track that.

**Comment by mk0sojo** [comment]
Thanks @stevejgordon . The Mediatr handlers are done, but some updates to the invite controllers are still required to call the handlers and accept / decline the invitation. Those are still not merged (still under review in PR #2009) so I will probably wait for that to get merged before finishing this.
