### ISSUE TITLE
Itinerary Details - Filtering

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2020]
When I filter the linked requests on the itinerary details page if no results are included in the filter I loose the ability to remove or adjust the filter.

Expected Result: When I apply a filter within the Itinerary Details (admin) page (request section), it should return any requests matching that filter. When no requests match, it should allow me to remove the filter or change the filter values.

Actual: The filter and the requests table are removed from the page and I am unable to adjust / remove the filter. There is no indication that a filter is applied. The only way to recover is to use the browser back button. Refreshing is not an option as it re-applies the form submission.

This needs to be fixed to ensure that an applied filter can be adjusted if it returns zero results.

**Comment by DanKline** [comment]
Id like to look at this one, but I don't see how to navigate to the Itinerary page.

**Comment by mk0sojo** [comment]
Taking a quick look at this the actual bug is quite easy to fix.
There is another problem however, when filtering it always looks for the matching Request.ItineraryId but this never seem to get set.
I guess a good place to set it would be on the Select Request page? Might be a problem with Requests already existing though.

**Comment by waiholiu** [comment]
Hi I've only just started trying to looking through this project today so excuse my ignorance, but I'm wondering why ItineraryId even needs to exist in the Request table because there is a joining table called ItineraryRequest that captures which itinerary each request belongs to, making that extra field redundant. And as far as I can see, it never actually gets set.

So I suspect the solution would be either
1. populate that field on the Add Request as you mentioned and maybe also add a database migration that populates this field for already created requests.
2. change the requestlistitemsqueryhandler.cs to query itinerary.itineraryId instead of itineraryId. 

```
            if (message.Criteria.ItineraryId.HasValue)
            {
                results = results.Where(r => r.Itinerary.ItineraryId == message.Criteria.ItineraryId.Value);
            }
```

instead of 

```
            if (message.Criteria.ItineraryId.HasValue)
            {
                results = results.Where(r => r.ItineraryId == message.Criteria.ItineraryId.Value);
            }
```


@mk0sojo  - let me know if you don't get a chance to do this one. I'm trying to understand how this project works so I'm trying to find little issues in which I can contribute.

**Comment by mk0sojo** [comment]
@waiholiu I went for solution 2 that you suggested in this case - thanks. I had already done the changes to the Itinerary details controller and view so it was almost done anyways.

**Comment by mk0sojo** [comment]
It might be worth considering making the filter an AJAX call to not update the whole page every time we want to change the filter.
