### ISSUE TITLE
Details action on Campaign controller passes wrong ViewModel to DetailsView

### ISSUE THREAD

**Issue by anobleperson** [HTBox/allReady#2076]
The code below (from CampaignController.cs) returns a CampaignViewModel, however the Details view expects CampaignDetailViewModel
```csharp
        [HttpGet]
        [Route("~/[controller]/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var campaign = await GetCampaign(id);
            if (campaign == null || campaign.Locked)
            {
                return NotFound();
            }

            ViewBag.AbsoluteUrl = UrlEncode(Url.Action(new UrlActionContext { Action = nameof(CampaignController.Details), Controller = ControllerNames.Campaign, Values = null, Protocol = Request.Scheme }));

            return View("Details", new CampaignViewModel(campaign));
        }
```

I haven't analysed the difference in properties between the two view models to see how serious the problem is.

**Comment by mk0sojo** [comment]
Looking at the Details view it looks like it expects a CampaignViewModel.
There is however a Details view in the Admin area that expects a CampaignDetailViewModel which it looks like it is getting from the CampaignController in the admin area.

**Comment by stevejgordon** [comment]
I've taken a look and everything appears in order.

@anobleperson I think I can see the issue though. VS 2017 intellisense is currently warning of the model mismatch because it seems confused on which view (admin vs normal) will be returned. I've stepped through and despite this incorrect warning in VS, the site seems to function as expected and the correct view is returned.

I'll try to investigate further to see if this is a tooling bug. For now I'll close this issue as our code seems to work as expected.

**Comment by anobleperson** [comment]
Okay, thanks @stevejgordon for the detailed investigation and explanation.
