### ISSUE TITLE
Fix Linux/Mac documentation

### ISSUE THREAD

**Issue by chezuma** [HTBox/allReady#2166]
Hi,

I did a fast scan of the issues, so forgive me if it's already on the agenda. 

I forked the repo and hoped I could help out with some issues, only to find out that this project only works on windows platform due to the dependency of the full dotnet framework. 

Is there an easy way to get it to run on linux / mac os x? Or do you have dependencies that make it hard to go full crossplatform? 

I would like to be at help to do this if there are no blockers due to external dependencies. 

best regards :)

**Comment by dchristensen** [comment]
@chezuma The web application has been moved to .NET Core 2.0.  I would recommend going through the getting started guide for [Mac](https://github.com/HTBox/allReady/wiki/Running-on-Mac-OS-X) or [Linux](https://github.com/HTBox/allReady/wiki/Running-on-Linux), which should help you get all of the dependencies setup and your environment configured correctly.  Feel free to respond with and specific issues you run into with those guides.

**Comment by chezuma** [comment]
Hi, 

I couldnt follow the instructions because I couldn't do a dotnet restore in a directory with multiple solutionfiles. I had to go into allReady/AllReadyApp/Web-App/ to do the restore and the build to get it to work. 

The rest of the instructions was correct as far as I experienced. 

Should I update the wiki? or maybe create a bash script for macOS ? 

Thanks for your time.

**Comment by jonparker** [comment]
Hi @chezuma,

I managed to get the website to build on my Mac by running: dotnet restore AllReadyWebOnly.sln

**Comment by chezuma** [comment]
@jonparker, ofc that is an option, but the documentation states otherwise and should be fixed so that others don't have to fumble around with that for 10 minutes :)

**Comment by jonparker** [comment]
@chezuma Yes I agree. Not having done much dotnetcore I didn't know that you can pass an sln file as a parameter to dotnet restore. The reason I mentioned it to you was because I wasn't sure if you knew about it either.
I already did a PR which has been merged to include the link to the Mac setup instructions as it wasn't easy to find.
I think the current devs on this project are all running Windows so it might be up to us to keep the Mac support up to date.

I haven't got a windows machine at home but I do have some free azure credit which I have used to create a win 2k16 vm with vs2017 to do windows stuff.

**Comment by VishalMadhvani** [comment]
I've been developing on a mac and while the experience isn't quite as nice as VS on windows, it does work. Feel me to ping me if you run into any issues.

As for updating the wiki's, I think it would definitely be appreciated.

**Comment by stevejgordon** [comment]
I agree, if the wiki is not quite right for Mac/Linux users it would be good to tweak it.

**Comment by jonparker** [comment]
@stevejgordon I've updated the wiki to include the sln file in the dotnet restore command. So I think this issue can be closed.
