### ISSUE TITLE
AllReady.ScenarioTest

### ISSUE THREAD

**Issue by VishalMadhvani** [HTBox/allReady#2169]
This doesn't seem to be used.
Can someone shed some light on it?
Might be best to delete it if it is dead code.

**Comment by MisterJames** [comment]
Yeah, it's looking like it's been a while since we revved on this. We might need to re-evaluate.  We'll chat about this in the coming days. Thanks @VishalMadhvani !

**Comment by dchristensen** [comment]
I think these were originally removed from the AppVeyor builds due to them causing the builds to take too long and therefore timing out.  I know I did some work to get them updated a couple months ago.  I took a couple minutes tonight to look at them and got the the project upgraded to the .NET Core style project files and got the tests running, although several were failing.  If I get a few minutes this weekend I'll see if I can fix the tests and get a PR in.

I guess the next question would be if we feel like we're getting enough value out of these tests to warrant maintaining them and re-integrating them into the AppVeyor process.
