### ISSUE TITLE
First and last name validation

### ISSUE THREAD

**Issue by dracan** [HTBox/allReady#2249]
When trying to register a new user, the registration form fails ...

![image](https://user-images.githubusercontent.com/567988/35168015-61fa5996-fd4f-11e7-8daa-ed4a2312fa0f.png)

Looking at the code, the `AllReady.ViewModels.Account.RegisterViewModel` has this regular expression ... `(.*?)\s([\wáâàãçéêíóôõúüÁÂÀÃÇÉÊÍÓÔÕÚÜ]+\-?\'?\w+\.*?$)`, which seems to have been added in #2148. Not sure this is right.

**Comment by redware** [comment]
I am getting this error too.

**Comment by thelem** [comment]
I'll pick this up

**Comment by thelem** [comment]
The regular expression above looks for: any character, followed by whitespace, followed by at least one letter or number including accented letters, followed by some special characters, followed by white space, followed by one or more periods.

I've changed it so that it looks for at least one letter (including the same accented letters), number or a small list of special characters and made sure there are no characters before or afterwards.
