### ISSUE TITLE
Cannot unenroll from a task

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#236]
There is an "unenroll" link, but it does not appear to do anything yet.  When I backed out to the activity and selected the task again, it appears that it has unenrolled me, but that is not clear for the user.  There should be a confirmation for the user that unenroll is completed.

![image](https://cloud.githubusercontent.com/assets/8798159/11018086/03a404e8-856d-11e5-8b74-f4c570890c30.png)

**Comment by bcbeatty** [comment]
Also see #183

**Comment by cecilia-donnelly** [comment]
Agreed with @Harmonym.  At the very least, clicking Unenroll should immediately redisplay "Volunteer," without waiting for the user to manually refresh the page.  I don't _think_ this is blocked on #183, since "Unenroll" does seem to have some effect already.  This issue is just a display / UI problem.

**Comment by tonysurma** [comment]
Thanks I triaged this for our next release

**Comment by ksk100** [comment]
I'll do this if no one else is working on it?

**Comment by BillWagner** [comment]
@ksk100 I assigned it to you. Thanks!
