### ISSUE TITLE
New User Registration Workflow - Name, e-mail, sms

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#261]
Prompt, but don't require, new users to supply additional profile information either after they have set up initial log-in through FB, Twitter, MSFT account.

Request:
Name
E-mail
Phone number
Phone number type (drop-down)

Note: mobile numbers will be used for SMS notifications.

**Comment by stevejgordon** [comment]
Please assign me to this issue and I'll start having a look during this week.

@tonysurma My only question at this point is around the phone number type dropdown. If I look at the app currently where we add a phone number it seem to assume all numbers are mobile since it intends to send a verification SMS? Should there also be a concept of a landline?

**Comment by tonysurma** [comment]
@stevejgordon good question, let me noodle that.  Initial thought is guide to mobile preferred and maybe not a drop down type but a [ ] for mobile can receive txt messages or something like that...

**Comment by stevejgordon** [comment]
@tonysurma Just wondering if the PR resolved this or if we need more work (perhaps new issue/story) to allow phone types?

**Comment by BillWagner** [comment]
Closed per PR #485.
