### ISSUE TITLE
404 error on log-off

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#277]
In the -d deployment, I received a 404 error when I clicked to Log-off as a user.

![image](https://cloud.githubusercontent.com/assets/8798159/11022706/0da410ac-861a-11e5-92e5-5b0298ed363c.png)

**Comment by dpaquette** [comment]
I couldn't reproduce this on my local machine. Is anyone else able to reproduce?

**Comment by ksk100** [comment]
No.  

Could it be that somehow the browser has made a `GET` request to /Account/LogOff, and that's the source of the problem, because there is only a `LogOff` action for the Post method?

(If manually navigate to that URL I see nothing at all; no error, but nothing rendered, and I'm not logged off).

**Comment by Harmonym** [comment]
I'll test it again tomorrow & see if I can repo it  and provide more detail. I was able to trigger it twice within a few minutes during the event Sunday, but it wasn't 100% consistent.

Sent from my Windows Phone
________________________________

**Comment by tonysurma** [comment]
@Harmonym thanks I will prioritize this after you see if it is reproducible

**Comment by Harmonym** [comment]
Thanks! I just tested it again on -d w/ a couple of different login methods and couldn't repo it, so we can probably close it for now.

Sent from my Windows Phone
________________________________
