### ISSUE TITLE
Duplicate social media code in layout and layout main page

### ISSUE THREAD

**Issue by JesseLiberty** [HTBox/allReady#396]
We should create a partial view to refactor this duplication

**Comment by dpaquette** [comment]
I don't think that _LayoutMainPage.cstml is used anywhere. If that is the case it should just be removed

**Comment by dpaquette** [comment]
Ah never mind. I see that it is used by Home\Index.cshtml.  I wonder if this is necessary. Would be nice if we could get down to a single layout

**Comment by ksk100** [comment]
I'll do this and then open another issue for investigating the possibility of getting down to one layout.

There is a slight difference in the footer styling on the main page compared to everything else; the font is smaller.  It's (homepage):
![image](https://cloud.githubusercontent.com/assets/6615834/11714678/d6a58116-9f33-11e5-9ed2-945db28ab2b0.png)

Versus (all others):
![image](https://cloud.githubusercontent.com/assets/6615834/11714687/e64f6f14-9f33-11e5-9e58-7aed33710441.png)

Does anyone know if there was a reason for this?  Or whether this is still desired?  I think the smaller looks better, as it draws less attention away from the more important bits of the page.

Also, the footer on all pages except the home page is slightly misaligned because the `footer` tag appears in the containing `div` rather than on a level with that `div` and the `header` tag.  I'll sort this out too.

**Comment by ksk100** [comment]
This was closed by commit cfdcceac3b56ec8d501613a82c78fa23ae0ae065.

**Comment by BillWagner** [comment]
@ksk100 Thanks. Closing now.
