### ISSUE TITLE
KO bindings fail on activity page when tooltip string includes an encoded apostrophe

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#449]
When the tooltip for the little round ? helpers contains an encoded apostrophe, `knockout-bootstrap` fails to apply the bindings.  The apostrophe is encoded properly, so I think there is a bug with `knockout-bootstrap` (I'll submit a Github issue for it).

The problem is seen on the Activity page with the sample MD skill, the description of which is "Trust me, I'm a doctor".  

A workaround is simply to swap the quotes styles.

**Comment by mheggeseth** [comment]
The problem is in the Volunteer popup that allows a user to associate new skills, right? That's the only place where Razor is emitting content into a KO binding. The "Trust me, I'm a doctor" tooltip works in other places like skill admin and activity admin because I've tested it, so I'm pretty sure it's not a problem with the KO-BS library. I don't remember why I decided to write that part with Razor instead of pure Knockout bindings, but I don't see any reason why it shouldn't be switched. That should fix it.

**Comment by ksk100** [comment]
Yes that's right, just on the popup.

It is possible to reproduce the problem in a simple HTML file (outside the allReady context) using ko-bs; if the apostrophe is hard coded (but escaped) in the tooltip then the tooltip handler from ko-bs won't bind it; if the apostrophe is in some field on the KO view model then it's fine, which is why the others work.

Anyway, I'm happy to go ahead and change it to use the KO view model if that's best.

**Comment by mheggeseth** [comment]
Yeah, go ahead and switch it to KO. Each required skill in the KO view model already has a property added to it called IsUserSkill. So just rendering required skills that the user doesn't already have should be pretty easy.

**Comment by mheggeseth** [comment]
Just out of curiosity, is the single quote escaped like `&apos;` or like `\'`?

**Comment by ksk100** [comment]
It's escaped as `&#x27;`; the error occurs with `&apos;` too, but actually not with `\'`.  

Maybe that's the root of the problem: ko-bs using Javascript escapes but Razor escaping with HTML entities?
