### ISSUE TITLE
User.GetTimeZoneId() does not return user time zone Id

### ISSUE THREAD

**Issue by bluechrometouch** [HTBox/allReady#462]
This method returns a null value for the user despite having a user time zone set. This method is being used in Activity.cshtml.

Currently testing with the default Administrator@example.com account.

**Comment by bluechrometouch** [comment]
Despite having a default time zone in the AspNetUsers table,users still need to have a time zone added to AspNetUserClaims table.

Adding such a claim on user registration and seeding users data could be a fix?

**Comment by dpaquette** [comment]
I will take a look. I think some changes to Identity in RC1 broke this because it was working previously. I ran into a similar problem with IsUserType yesterday.

Please assign to me

**Comment by BillWagner** [comment]
Assigned to @dpaquette

**Comment by dpaquette** [comment]
Okay I had a look at this and it is currently working as designed.

We don't require the user to provide timezone info at the time of registration so we only actually set the claim if the user explicitly edits the profile and changes their timezone setting. I think this is ok since the user's timezone isn't actually required for them to use the system. We will also be prompting the user to complete their profile as part of #262 so I think this will help.

**Comment by bluechrometouch** [comment]
Ok, I think this can be closed then.
