### ISSUE TITLE
Add support for "Type T: Task Manged" activities

### ISSUE THREAD

**Issue by mmoore99** [HTBox/allReady#507]
This is sub issue of #504 

More detail to follow.

**Comment by mmoore99** [comment]
For this type of activity the following is true:

- Tasks are shown to volunteers
- Volunteers volunteer for Tasks
- Admins can re-assign tasks to volunteers
- Re-assignment communication is only sent to Volunteers when it results in change outside of assigned timeframe and they can accept/reject task assignment
- Reminder sent ahead of Activity with option to respond as 'no longer able to volunteer'

**Comment by mmoore99** [comment]
I am currently on the code for this issue.

**Comment by mmoore99** [comment]
Submitted PR #523

**Comment by mmoore99** [comment]
@tonysurma @OhMcGoo when setting up a `TaskManaged` activity:

- Should we prevent entry of the `Volunteers Required` field in the activity in order to prevent confusion since the `Volunteers Required` will be specified for each task?

- Same question for `Start Date` and `End Date`? Rather entering these dates manually we could calculate them from the dates in the tasks.

- It would also seem that there is not a need to enter `Required Skills` for the activity itself, since they will be entered for each task.  Is that true?  If so, would it be beneficial to provide the option to enter   `Required Skills` that would be automatically replicated to all tasks in the activity.  For example, if we had the following activity/task structure and had a large number of tasks:
  - Activity: Install fire detectors in Queen Ann District
    - Task: Install - 2300 Main Street
    - Task: Install - 3250 Marsh Drive
    - Task: Install - 1234 Norris Canyon Drive

- In this case all of the tasks might have a skills required of "Electrician" and "Driver".

I would appreciate your feedback on this, as I am in the process of trying to finalize this issue.

Thanks.

**Comment by OhMcGoo** [comment]
@mmoore99, @tonysurma: See my answers inline.

Should we prevent entry of the Volunteers Required field in the activity in order to prevent confusion since the Volunteers Required will be specified for each task?

**I agree that Volunteers Required should be set at the Task level, however, we need to ensure that an individual Volunteer can be assigned more than one task during an Activity. For example, a Volunteer may be assigned to the task of delivering supplies to a staging area pre-Event. They, then, could asked to join an installation team later.**

Same question for Start Date and End Date? Rather entering these dates manually we could calculate them from the dates in the tasks.

**I think a *bookend* date range should be set at the Activity level. Then, Task-specific date ranges can be set within bookend dates.**

It would also seem that there is not a need to enter Required Skills for the activity itself, since they will be entered for each task. Is that true? If so, would it be beneficial to provide the option to enter Required Skills that would be automatically replicated to all tasks in the activity. For example, if we had the following activity/task structure and had a large number of tasks:

**I'd lean towards setting Required Skills, universally, at the Activity level. @tonysurma feel free to disagree. I could then imagine, then, a pop-up menu displaying the pre-specified Skills on the Task creation page. In addition, over time, I could see Skills being managed at the Organization level.**

Activity: Install fire detectors in Queen Ann District
Task: Install - 2300 Main Street
Task: Install - 3250 Marsh Drive
Task: Install - 1234 Norris Canyon Drive
In this case all of the tasks might have a skills required of "Electrician" and "Driver".

I would appreciate your feedback on this, as I am in the process of trying to finalize this issue.

**Hope this helps!

Jim "My brother's name is Mike" McGowan**

Thanks.

**Comment by mmoore99** [comment]
@OhMcGoo cc: @tonysurma  Thanks for the feedback.  I have some further questions for clarification:

> I'd lean towards setting Required Skills, universally, at the Activity level. @tonysurma feel free to disagree. I could then imagine, then, a pop-up menu displaying the pre-specified Skills on the Task creation page. In addition, over time, I could see Skills being managed at the Organization level.

Let me play back to you how I am interpreting the above statement and then you can correct me where I am off base.  You would envision:
-  that there would be a "master" list of skills to be set and maintained at the Organization level.

- Then, when an Activity is created/edited, the Activity add/edit page would allow for selecting the Activity's `Required Skills` from the **Organization's "master"  list of skills**.  These selections would then comprise the "master" list of skills for the Activity.  

- Then, when a Task is created/edited,  the Task add/edit page would allow for selecting its `Required Skills` from the **Activity's  "master list of skills**.

Is this correct so far?  If so, then should there be an option to automatically pre-populate the `Required Skills` for all tasks in the activity, or is it better left to have this as a manual process?

Thanks for your help, it is sometimes hard to flesh out requirements like this in a written dialog since things can be easily misinterpreted.

**Comment by OhMcGoo** [comment]
@mmoore99 (cc @tonysurma): I like it! At the Activity level could we create 'bundles' of skills?
