### ISSUE TITLE
Invalid zip code in Campaign Edit page causes internal server error - correct workflow

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#530]
Extension of issue #470 to make a new workflow fix and not just remove the error and for that matter we need to get on top of whole geo stuff anyways

To Start:
I've seen this same issue in the Create Campaign flow also. I guess this needs some discussion on how this should function. 
- Should it be an autocomplete from the available post codes in the PostalCodeGeo table? 
- What if someone is adding a campaign and their postcode doesn't exist yet? 
- How is the PostalCodeGeo anticipated to be managed to add/remove them?

**Comment by mgmccarthy** [comment]
@tonysurma, is there a reason we can't make PostalCode a required field when creating a Campaign? If the reason is the PostalCodeGeo lookup will fail, then my question to that is, what is PostCodeGeo table used for? Is it to generate this map?
![image](https://cloud.githubusercontent.com/assets/2428993/16814357/6d92d348-4903-11e6-8fcf-28fb17e7c5e6.png)

If that's the case I guess a couple things:

1. disregarding our current lookup failure on PostCodeGeo, does it make sense for a Campaign to be created with no postal code? Is we don't require this up front, then this results in potentially a lot of checks on the read side for string.IsNullOrEmpty checks, etc... to avoid this, it's easier to require the postal code when we create a Campaign
2. taking PostCodeGeo table into account, would it be possible to show some text that says something along the lines of "to see this Campaign's Location on a map, please click here to fille out x, y, z". (or anywhere else on the UI which relies on the data in PostalCodeGeo to be available to see a map). Basically, something that allows us to still create a Campaign w/out postal code, but we end up hiding any UI elements that depend on PostalCodeGeo table to have matching data for that postal code

**Comment by stevejgordon** [comment]
At the moment we don't enforce a check any long against the postcodegeo table. I think that may be retired but would have to double check that. Either way, we don't blow up at the moment. We may need to review how this affects mapping etc as you can pass in any text right now and it is accepted. Will close this particular issue.
