### ISSUE TITLE
Replace .Wait()/.Result() with .GetAwaiter()/.GetResult()

### ISSUE THREAD

**Issue by SeanFeldman** [HTBox/allReady#547]
For synchronous code that is using asynchronous library (similar to the code in `NotificationsProcessor`), using `.Wait()` or `.Result()` is undesirable and should be replaced with `GetAwaiter().GetResult()` to avoid deadlocking and get a clean exception (if thrown) instead of `AggregateException`.

Reference: https://github.com/aspnet/Security/issues/59

**Comment by dpaquette** [comment]
Is there anywhere outside of `NotificationsProcessor` where we are doing this?

**Comment by SeanFeldman** [comment]
`AllReadyDataAccessEF7.Skill`
`QueueStorageService`
`NotificationsProcessor`

**Comment by SeanFeldman** [comment]
@dpaquette are you working on this one or should I start with it?

**Comment by dpaquette** [comment]
You go ahead. I only asked because I remembered seeing some weird async stuff in the original `AllReadyDataAccessEF7.*` code.  

All those `AllReadyDataAccessEF7.*` partial classes are considered legacy and we have been working to replace them. Make sure you check to see if those methods are used before you spend the effort fixing them. I would rather see the methods deleted if possible.

**Comment by SeanFeldman** [comment]
PR: #552
