### ISSUE TITLE
Make code async all the way

### ISSUE THREAD

**Issue by SeanFeldman** [HTBox/allReady#548]
Code that starts async 
  `CloudQueueClient.AddMessageAsync()`

and ends as async 
  `AuthMessageSender.SendSmsAsync()`

should be async all the way and not converted into synchronous in the middle    `QueueStorageService.SendMessage()` & `NotifyVolunteersHandler.HandleCore()`

**Comment by SeanFeldman** [comment]
PR https://github.com/HTBox/allReady/pull/570

**Comment by mgmccarthy** [comment]
@SeanFeldman, I need a little help with a Task/async unit testing problem. 

I've been slowly refactoring ActivityApiControllerTests, and I'm currently working on testing the UnregisterActivity action method.

First, some background on the controller and unit tests. In the unit tests testing UnregisterActivity, there is ServiceProvider/DbContext setup work being done in the GetActivityApiController method. This method returns a new controller instance, but also sets an in-memory database in motion that is seeded with test data for testing this line in the controller:

`await _allReadyDataAccess.DeleteActivityAndTaskSignupsAsync(id);`

Basically, both existing unit tests test the outcome of data changes performed in this method, but looking at the context calls before assertion:

``` 
var context = _serviceProvider.GetService<AllReadyContext>();
varr numOfUsersSignedUp = context.Activities.First(e => e.Id == recordId).UsersSignedUp.Count;
Assert.Equal(0, numOfUsersSignedUp);
```

you'll see what's really being tested here is the:
`AllReady.Models.AllReadyDataAccessEF7` classe's:
`Task IAllReadyDataAccess.DeleteActivityAndTaskSignupsAsync(int activitySignupId)` method.

In this method, there are multiple DbContext operations being performed.

Seeing how the the two unit tests in ActivityApiControllerTests (UnregisterActivityShouldRemoveActivitySignup and UnregisterActivityShouldRemoveActivitySignup)  really test the `DeleteActivityAndTaskSignupsAsync` in the `AllReadyDataAccessEF7` class, I moved to break these tests out into a test class written against `AllReadyDataAccessEF7`.

I've run into a problem when trying to test the null return value in `DeleteActivityAndTaskSignupsAsync`. The method looks like this:
![image](https://cloud.githubusercontent.com/assets/2428993/13541006/bfb16a4c-e227-11e5-8700-608bc4013c8e.png)

yet, when write a test against the null value being returned:
![image](https://cloud.githubusercontent.com/assets/2428993/13541027/ecdb0e92-e227-11e5-8555-82865706dbc0.png)

I'm getting this error:
"cannot assign void to an implicitly typed variable"
"cannot assign 'void' to an implicitly typed local variable"

Since I have no experience with Task or async, I figured I'd reach out to you to see if what I'm trying to do is even possible.

The one question I do have is shouldn't the `DeleteActivityAndTaskSignupsAsync` method be returning `Task<int>` instead of `Task`? `_dbContext.SaveChangesAsync` returns `Task<int>`. If the method did return `Task<int>`, would it even make a difference?

Thanks

**Comment by SeanFeldman** [comment]
@mgmccarthy if understood correctly, `DeleteActivityAndTaskSignupsAsync` is a "command" to delete a given user w/o any meaningful value to come back. The `int` being returned by EF is the number of affected records in the database that this code is not interested in. As such, in a synchronous version it would return nothing, i.e signature would be `void`. Because we've switched to `async`, we have to return a `Task`. In situation like this you could return `Task.CompletedTask` instead of null (.NET 4.6) or `Task.FromResult(0)` (older version of .NET).

Let me know if that helps.

**Comment by mgmccarthy** [comment]
`DeleteActivityAndTaskSignupsAsync` is a method off of the `AllReadyDataAccessEF7` class... it should be a command (and will be when I've done moving the ActivityApiController to use mediatR.

I'll try to return either of those types you mentioned and see how it goes.

Seems that a lot of the methods in the `AllReadyDataAccessEF7` partial classes contain some logic or a couple of calls to different entities on DbContext.... I'm thinking it will be good to move all unit tests that might be masquerading as controller unit tests into an '`AllReadyDataAccessEF7Tests` class.

A lot of the existing unit tests that are in the controller tests stand up a service provider as well as an in-memeory DbContext to run to provide some data to the data access class in order to run the tests...

a "light" integration test in a way...

either way, thanks

**Comment by mgmccarthy** [comment]
@stevejgordon. What were your actual changes to ActivityApiControllerTests from this commit?
[https://github.com/HTBox/allReady/commit/9944a39604040a2fa3cc8c024638f6830f0b0753](https://github.com/HTBox/allReady/commit/9944a39604040a2fa3cc8c024638f6830f0b0753)

I'm only asking, b/c I'm pretty deep into the unit test/refactoring of ActivityApitControllerTests right now (Issue #587), and merging from a rebase could be particularly challenging when I'm done. I just want to make sure I understand the actual changes before trying to rebase.

Thanks

**Comment by mgmccarthy** [comment]
@SeanFeldman, I have another async/await question that I stumbled upon while writing unit tests for TaskApiController.

In the `Post` method, there are checks that could result in a `HttpBadRequest` or `HttpUnauthorized` being returned based on some rule checks:
![image](https://cloud.githubusercontent.com/assets/2428993/13758880/1352a6de-ea02-11e5-9e12-ee799758efd2.png)

if all rule checks succeed, then the last line executed is:
`await _allReadyDataAccess.AddTaskAsync(model)`

when looking at this implementation, this method returns a Task, but also can thrown an exception:
![image](https://cloud.githubusercontent.com/assets/2428993/13758929/4a5f8e26-ea02-11e5-8e95-77ba1a562ecd.png)

How can I unit test returned values as the result of failed rule checks if:

- the Post method returns `async void` (also, I read a couple places that returning async void is bad.. it this true in this case?)
- `AddTaskAsync` is returning a Task?

**Comment by SeanFeldman** [comment]
@mgmccarthy `void` on the controller should be replaced with `Task`. Because there's an `await`, method will be `public async Task Post(...)`.

I'm not sure why we need the value returned by `AddTaskAsync`, but regardless, if you mock data access object, you'll need to return a task. Either a [successful](https://github.com/HTBox/allReady/blob/master/AllReadyApp/Web-App/AllReady.UnitTest/Controllers/OrganizationControllerTests.cs#L156) or faulted task.

If you run into issues, let me know, perhaps we can pair up.

**Comment by mgmccarthy** [comment]
@SeanFeldman I was thinking I could make the controller method return:
`public async Task<IActionResult> Post(...)`

since we're returning `HttpUnauthorized` or `HttpBadRequest` based on rule checks.

If I go this route I could add:
`return new HttpStatusCodeResult((int)HttpStatusCode.OK);` as the final line in the action method, but I'm not too sure what the "standard practice" is for returning anything from Post actions on a WebAPI controller. In other words, I don't know what http status code is traditionally returned from a successful POST operation.

As far as returning Task from `AddTaskAsync`, I'm holding off on any API changes to the IAllReadyDataAcess interface right now until allReady does their pilot to the Red Cross, so although I agree with you (we don't need to return anything from this method really), I can't make that change right now.

Also, do we really need to throw an exception from the `AddTaskAsync` method? We're already checking for the existence of the task in the controller:
```
var taskExists = GetTaskBy(task.Id) != null;
            if (taskExists)
                return HttpBadRequest();
```
but this last question is probably a question for the allReady team.

**Comment by SeanFeldman** [comment]
What fiddler shows as returned status code when you run it today with `void`?

**Comment by mgmccarthy** [comment]
@SeanFeldman, I switched to my master branch locally and made sure I'm up to date with remote origin to test this.

So far, 200's are returned for both POST and DELETE. I"m still trying to get together valid json for the post as there are a LOT of properties that are set on the AllReadyTask on a POST. 

What has not been working is any of the `HttpUnauthorized` or `HttpBadRequest` calls, b/c none of them uses a returns statement to return the result. Here's an example:
![image](https://cloud.githubusercontent.com/assets/2428993/13812302/ce5022f4-eb51-11e5-90b0-afda275166e2.png)

Here, `HasTaskEditPermissions` returns false, yet b/c there is no return statement with `HttpUnauthorized`, the code continues to execute and calls `DeleteTaskAsync`. Not good. My current feature branch for TaskApiController refactoring fixes this.

As far as what type of response codes should be returned, I've found these resources online:
- http://aspnetmvc.readthedocs.org/projects/mvc/en/latest/getting-started/first-web-api.html: "The CreatedAtRoute method returns a 201 response, which is the standard response for an HTTP POST method that creates a new resource on the server"
- http://stackoverflow.com/questions/2342579/http-status-code-for-update-and-delete
- http://stackoverflow.com/questions/1860645/create-request-with-post-which-response-codes-200-or-201-and-content

Information about returning a `Task` or `asycn Task` from a Web Api controller:
- http://stackoverflow.com/questions/29964819/async-return-task-or-await-first-in-asp-net-webapi
- http://stackoverflow.com/questions/12144077/async-await-when-to-return-a-task-vs-void?rq=1

DISCLAIMER: I don't know Web API that well. I've only written a couple methods that do GET's, but I've never been immersed in all the allowable REST calls against a Web API controller.

**Comment by SeanFeldman** [comment]
I'd try to return a `Task` (public async Task Delete(int id)` and see if WebAPI knows how to handle response properly.

**Comment by mgmccarthy** [comment]
@SeanFeldman, as long as these three methods (`Post, Put and Delete`) also need to return:
```
HttpUnauthorized
HttpBadRequest
```
both of which inherit from `ActionResult`, I can't return only a `Task`. I need `Task<T>` in order to return those types to the caller in the case where the call failed for some reason.

I was talking to mmoore99 the other day about this controller, and he said he did not work on the `Post, Put and Delete` methods at all, they were there when he added `RegisterTask, UnregisterTask and ChangeStatus`.

I might need to dig around to see if these three methods are even worth all this investigation. 

I DO understand, however, why you want me to try to return a `Task`. I might try that locally within the feature branch, but I already submitted a PR last night for this refactoring, and for now, `Post/Put/Delete` return `public async Task<IActionResult>`

**Comment by SeanFeldman** [comment]
:+1: my offer to pair if needed is still on power.

**Comment by mgmccarthy** [comment]
@SeanFeldman, I'd love to pair and get a second set of eyes on this. When do you wan to do it, and how do you want to do it?

**Comment by SeanFeldman** [comment]
Evenings. I'm in MST. Can host zoom session.

**Comment by mgmccarthy** [comment]
@SeanFeldman, i might be available tonight after 9pm EST. I have a 5 month old at home, so I'm never really "in control" of my time after work. Did you want to aim for 9pm EST (I think MST is one hour behind?) for the zoom session?

**Comment by SeanFeldman** [comment]
9PM EST is 7PM MST (2h apart).
I'll try to get online, but need to pick up kids. Let's take this to email. Mine is feldman.sean on gmail.
