### ISSUE TITLE
Refactor controller actions to use Mediator 

### ISSUE THREAD

**Issue by mikesigs** [HTBox/allReady#567]
This is a catch-all issue for refactoring controllers to use the Mediator patter (i.e. Command + Handler)

**Comment by mmoore99** [comment]
@mikesigs just wanted to let you know that I am actively working in the `ActivityApiController` and `TaskApiController` for functionality reuired in issues #506, #507 and #508.  I  would appreciate your holding off on Mediator pattern refactoring on those controllers so we don't step on each other and get a bunch of merge conflicts.  Thanks.

**Comment by mgmccarthy** [comment]
@mmoore99, I'm currently working on HomeController. Just added unit tests and now refactoring to MediatR. Not too sure who else is doing controller re-factoring/unit tests right now. For now, when I take a new controller on (for adding unit tests and/or refactoring to MediatR), I'll let both your and @mikesigs know.

**Comment by MisterJames** [comment]
This thread is hereby marked as exhibit "A" in the case of "Reaching Critical Mike Mass".

**Comment by mgmccarthy** [comment]
@MisterJames, I have a question about the folder structure that holds the queries/handlers/models for moving to MediatR in the context of controller refactoring. Is this a question I should be posting in this issue, or is it something I can contact you directly about?

**Comment by tonysurma** [comment]
@MisterJames srsly, I noticed that too.  It's a herd of cattle, a murder of crows, an internet of things, a merge conflict of developers and a ___________ of Mike's?

**Comment by BillWagner** [comment]
@tonysurma @MisterJames Keep it up, and we'll have to invoke The Highlander Rule.

**Comment by mikesigs** [comment]
I don't know if it's bad form to use GitHub issues to share funny videos... But this relevant (and funny). 

https://youtu.be/jedA1-bFvC8

**Comment by mgmccarthy** [comment]
@mikesigs, not too sure if the video was bad form, but it was funny.

**Comment by mgmccarthy** [comment]
@tonysurma, @MisterJames, @mikesigs, @mmoore99. Is this blanket refactoring to MediatR for ALL controllers a good idea?

For example, I'm currently working on the AllReady.Controllers.CampaignController. Its constructor only takes one dependency, IAllReadyDataAccess:
```
public CampaignController(IAllReadyDataAccess dataAccess)
{
    _dataAccess = dataAccess;
}
```

and it uses that dataAccess dependency for very simple queries:
```
var campaign = _dataAccess.GetCampaign(id);
_dataAccess.Campaigns.Where(c => !c.Locked).ToViewModel().ToList()
return _dataAccess.Campaigns.Where(c => !c.Locked).Select(x => new CampaignViewModel(x));
```

since these are such simple queries, the idea of creating one query, handler and model class per action method seem like needless abstraction. Even if we re-used some of the query/handler/models classes across multiple action methods in the controller or across controllers, what is this really buying us?

For more complex controllers (those that take many dependencies,have a lot of execution logic to test, or are executing complex queries against the data access), I can see where introducing MediatR can make the controllers less heavy, easier to unit test and more SRP-friendly, but for simple controllers like the ones I'm working on now, I'm not too sure if it's really needed.

Or, I'm totally missing the point of the issue, and we're only supposed to be moving to MediatR to send commands to handlers, and not to send query requests?

Thoughts?

**Comment by mikesigs** [comment]
I think the original motivation was to reduce the complexity (and # of dependencies) on the controllers. We could certainly be pragmatic about this and just focus on the more complicated controllers/actions. On the other hand, always doing things the same way has its virtues as well.

I was starting to do this refactoring is a means of getting my feet wet. But I'll admit the thought of refactoring every single controller and action, regardless of complexity, seems a bit daunting/tedious/overkill.

Anyways, that's my 2c. Curious to hear what the others have to say.

**Comment by MisterJames** [comment]
Pragmatism is okay. We don't need to refactor for the sake of refactoring, but, honestly, when creating new controllers is there any reason to not use the bus? For me, as long as we're thinking about it, I'm happy. 

All of the reasons listed above are valid, but the other point is to drop that data access class altogether. After all, what are we gaining by adding an abstraction over an abstraction with a pseudo-repository _that does everything_? IMO, queries, commands and handlers are simple to understand and contain everything needed for the task at hand unto themselves.

After a short while there will be queries that cover most aspects/entities in the database...queries aren't meant to be 1:1 with actions. Anywhere we're looking for campaigns, we can use the same query (in the context of the operation...so a query on the admin side might be shaped differently). 

By the way...I think that one issue+PR per controller is a good approach to this refactoring. Helps keep the size reasonable and gives a jump-in point for devs new to the project (as @mikesigs was).

**Great conversation folks**, thanks for caring enough to prod and ask. Feel free to add thoughts/comments/further questions.

**Comment by mgmccarthy** [comment]
@MisterJames, than thanks for the feedback. I understand how we're using CQRS now... especially the part about re-using (withing context, aka, admin vs. non-admin) queries, query responses (aka, "models"), commands and handlers. I'm going to keep moving forward with my controller refactoring and get MediatR in there.

**Comment by mgmccarthy** [comment]
@mmoore99, are you still doing work on TaskApiController? I'd like to take a crack and getting unit tests around it and refactoring to mediator, but I just looked at the history for the file, and I don't see a commit by you and in this thread, you said you were doing work with that controller

**Comment by mmoore99** [comment]
@mgmccarthy the changes I made to `TaskAppiController` are in PR #523, which is waiting to be reviewed.

**Comment by mgmccarthy** [comment]
@mmoore99 is it "safe" to start refactoring on TaskApiController? Seems like there are a lot of changes going on surrounding this controller. Would it be better to just get unit tests around it first then move to mediator later? I'm asking b/c you seem to have a good knowledge of how all the code in this controller ties back to the business requirements

**Comment by mmoore99** [comment]
@mgmccarthy I think it is probably ok to move forward with the move to mediator now that #523 has been merged. My work related to tasks is going to be moving toward the admin side for a while. Thanks for asking.

**Comment by mgmccarthy** [comment]
@MisterJames @BillWagner. Since I'm the steward of this Issue, I was just wondering how far do we take the refactoring to mediator? 

I've started to go through Controllers now and refactor out ISmsSender and IEmailSender. This change opts for specific messages worded in the language/context of what the controller is doing.

But where do we stop?

For instance, many of the controllers inject `UserManager<ApplicationUser>` and `SignInManager<ApplicationUser>`. Are these also to be considered abstractions we want to remove from the controllers and abstract with mediator?

I only see one instance where `UserManager<ApplicationUser>` is used outside the context of a Controller, and that's in `DeleteUserCommandHandler`. There are no instances of `SignInManager<ApplicationUser>` used outside controllers.

My two cents is we leave `UserManager<ApplicationUser>` and `SignInManager<ApplicationUser>` as inject-able dependencies in controllers. These already represent and abstraction on top of authorization/authentication ops. Creating a message per operation with mediator would only really move a call from a controller into a handler, and that's another level of abstraction. In my opinion, an "abstraction of an abstraction" is really not that useful.

It looks like @MisterJames initial intent was to remove the IAllReadyDataAccess dependencies from controllers, b/c in the future, it sounds like that might go away, and that is what we wanted to move to mediator.

I know there is a lot of P1 work going on right now, and that's where the the work should be done, but I was wondering what you're take on this task being almost "finished" is.

The only two controllers left injecting `IAllReadyDataAccess` are:
```
AllReady.Areas.Admin.Controllers.SiteController/SiteAdminController
AllReady.Controllers.TaskApiController
```

Thanks.

**Comment by BillWagner** [comment]
Adding @tonysurma to weigh in because of deadlines and demos.  Personally, I'd err on the side of finishing work in progress, rather than leaving it unfinished. It diminishes churn. It avoids re-work. 

And, as @MisterJames says above, as we separate more, queries become reusable, instead of bundled in commands.

**Comment by tonysurma** [comment]
As long as we stay on this side of may 16 we are good on timelines

**Comment by mgmccarthy** [comment]
@MisterJames

My last PR, #716, pretty much eliminates `IAllReadyDataAccess` from all controllers. If we want to stop at that (and maybe let me take `IEmailSender` and `ISmsSender` out of remaining controllers), then this Issue can be closed.

But, if we want to abstract calls to `UserManager<ApplicationUser>` and `SignInManager<ApplicationUser>` out of controllers, and move those calls to message via mediator, then i have a good amount of work left to do.

Let me know what you'd like me to do

**Comment by stevejgordon** [comment]
@mgmccarthy What are the pros for removing UserManager and SignInManager? As they are injected by the DI system and pretty clear on what they do, my personal view is that it would be unnecessary to abstract them further. I really like the CQRS pattern for the data access, just not sure we need Mediator elements for those identity parts.

**Comment by mgmccarthy** [comment]
@stevejgordon, that's what I'm hinting at. I see it as an "abstraction of an abstraction"... not really needed. And since `UserManager` and `SignInManager` are already used, the code written and some of the unit tests finished... it could be more trouble than it's worth...

one a side note, I really enjoyed your blog post: [Extending the ASP.NET Core 1.0 Identity SignInManager](http://stevejgordon.co.uk/extending-the-asp-net-core-identity-signinmanager). Thanks for sharing.

**Comment by stevejgordon** [comment]
@mgmccarthy Thanks, I'm glad you enjoyed it. It's taken a while to get my head around how it all works and I still have a lot to learn. I've started (but had not time for a while) to build out my own library that can plug in as middleware to setup user auditing stuff. My goal was to get it up on GitHub at some stage and maybe even make a nuGet package as well. Once I've proven it a) works and b) can be packaged I'll put something up. If nothing else I've learned lots!

**Comment by mgmccarthy** [comment]
@MisterJames @tonysurma @stevejgordon. I think this Issue is done. There should be no other controllers using any data access injection. I finished removing IEmailSender from a couple controllers a month or two ago.

The only thing still being injected into controllers are SignInManager, UserManager, etc... dependencies dealing with authentication and authorization, which we're going to leave.
