### ISSUE TITLE
Unit Tests: Improve Unit Test Coverage

### ISSUE THREAD

**Issue by mheggeseth** [HTBox/allReady#59]
The unit test project AllReady.UnitTest only has a 3 tests and only tests the ActivityApiController. Write more tests and improve the robustness of existing tests.

**Comment by peteraritchie** [comment]
I'm doing this

**Comment by rockfordlhotka** [comment]
I'm also working on this

**Comment by MKSessions** [comment]
We know we don't have the test coverage that we want.  We'd welcome anyone adding more unit test coverage.

**Comment by ericbrumfield** [comment]
Looking to pitch in, I'll start with ResourceAPIController to get my feet wet.

**Comment by Kritner** [comment]
This is probably silly as far as missing a setting or something, but when I run "Analyze Code Coverage -> All tests" in the web only solution (I'm trying to easily identity areas that still need test coverage)  it only shows that 33.33% of code is not covered.  The strange this is, that 33% is made up of only a total of 12 blocks (4 missing).  The only assembly showing up in the first tier of the drop down is AllReady.Models.dll.  Any ideas why my code coverage is clearly not checking out the code coverage of the entire solution?

**Comment by jonhilt** [comment]
Hello. I've been discussing with @BillWagner and @RichardCampbell  a proposal to to host a "hackathon" day at my company (codeweavers.net) to work on AllReady.

We're still in the planning stages but looking at the kind of areas we could work on for the day this seems like a gentle introduction for our developers (contributing to open source is new to most of them) and something which would add value.

Once we settle on a date, we'd be happy to take any gaps in the testing and look to plug those. Failing that, if there are any obvious areas/features for us to to look at (which would be of most benefit to the project) then please do let me know.

Thank you

**Comment by BillWagner** [comment]
@jonhilt I think that is an awesome idea. Let us know when you have the date finalized.

**Comment by DocHammoc** [comment]
I have a passion for unit tests ... so this may be a good place for me to jump in.

**Comment by BillWagner** [comment]
@DocHammoc That would be perfect. Note that some improvement has happened here since this issue has been created, but we're still not where we want to be.

**Comment by eisenpony** [comment]
Some people are having trouble running code coverage, so here is a spreadsheet with current numbers.
[Coverage.xlsx](https://github.com/HTBox/allReady/files/139273/Coverage.xlsx)

**Comment by mgmccarthy** [comment]
@mheggeseth and @MKSessions, I'd like to contribute to allReady. Looks like you just had a hackathon this past weekend and there have been unit tests added to the controllers. These controllers still have no unit tests:
CampaignApiController
ClosestLocationsController
HomeController
ManageController
MeApiController
TaskApiController

I'd like to start with writing unit tests for these unless there are any particular controllers out of the these that you do NOT want unit tests written for?

Thanks,
Mike

**Comment by mheggeseth** [comment]
@mgmccarthy Go right ahead. Start with the ones that that seem to be most used in the app (I'm not sure all of these are). For those you cover, create new, more specific issues that reference this one and then submit pull requests that fix the new issues.

**Comment by BillWagner** [comment]
@mgmccarthy I agree with @mheggeseth Dive in! Any additions here will be useful.

**Comment by mikesigs** [comment]
Any chance we want to use a library like Shouldly to make our Unit Tests a bit easier to write (and output easier to read)? I've used both FluentAssertions and Shouldly and would strongly recommend the use of Shouldly. It's simple to use, and it shows really easy to understand failure messages. See more in [the docs](http://docs.shouldly-lib.net/v2.4.0/docs).

Also, I am in the process of refactoring controllers to use MediatR #567. So any unit tests that get written right now will need to be refactored too. Could I suggest that instead of just writing more tests, that you first refactor the controller method to the MediatR pattern, then write unit tests for the resulting Handler? 

Here's a great post that shows what I think we're striving for with MediatR: https://lostechies.com/jimmybogard/2015/05/05/cqrs-with-mediatr-and-automapper/

**Comment by mgmccarthy** [comment]
@mikesigs, funny you should mention Shoudly. I just stumbled on that repository a week or two ago, and had a quick look. From an initial glance, it looked very fluent, and I liked the API. I have no experience with the framework yet. 

That being said, since I'm an nUnit guy, I'm kind of a fish out of water with the xUnit tests and it's slowing me down right now. If I'm moving slower than usual, and Shoudly offers a superior API to xUnit, then I might as well be slow and learn Shoudly at the same time.

I guess the one thing I'm not clear on, is Shoudly just a wrapper around an existing test framework or is it testing framework unto itself?

For MediatR changes, I use NServiceBus at my current job, so the approach of sending commands to "do things" or publishing "events" for things that have been done is very familiar to me. I find it a little "weird" that you send a request to execute a query, but I'm sure I'll catch on.

Will all controllers be refactored to MeidatR? If so, maybe some sample code from a controller and unit test for that controller that you're working on could give me an idea of what you're thinking so we're on the same page.

**Comment by mikesigs** [comment]
Shouldly is an "Assertion Framework". It doesn't replace xUnit, it just alleviates you from having to use `Assert.Foo` calls. For example...

Instead of writing:

```Assert.AreEqual(foo, 2);```

You write:

```foo.ShouldBe(2)```

It makes for much more readable code, and must better failure messages.

The MediatR stuff is still a work in progress for me. I started changing a couple methods on the ActivityController at the Hackathon on Saturday. See [this commit](https://github.com/mikesigs/allReady/commit/da82b2ad5bb0dbd5915b1abf963ba4fff726577a) for an example of what I've done so far.

One thing I don't like is that I'm explicitly checking for null and returning HttpNotFound(). An improvement to this (and something I think I'd like to attempt) is using ExceptionFilters. So in the RequestHandler we could throw a `new EntityNotFoundException()` or something and use an MVC ExceptionFilter to translate those kinds of exceptions into 404s.

**Comment by mikesigs** [comment]
I found this page to be extremely handy when starting out with xUnit.
https://xunit.github.io/docs/comparisons.html

**Comment by mgmccarthy** [comment]
@mikesigs, Shouldly looks good. Do we need approval from the overall project team to use it? Would using Shouldly act as a barrier to bringing other open source contributors aboard? Would sticking with xUnit assertions made it easier to get devs up and running quicker? That's a question I'm not qualified to answer.

As far as MediatR controller refactoring, i just looked at [your commit](https://github.com/mikesigs/allReady/commit/da82b2ad5bb0dbd5915b1abf963ba4fff726577a). I guess one question I have is why do you have to check for null? The code was not checking for null before when the query calls against allReadyDataAccess lived in the controller. 

in ActivityDetailQueryHandler, it looks like the model is being set to null:
`ActivityDetailModel result = null;`

instead of a new model instance:
`ActivityDetailModel result = new ActivityDetailModel();`

I don't understand why the model is set to null instead of instantiating a model class and then populating its properties from queries in the handler. This would eliminate null checking altogether.

In [Jimmy's handler sample](https://gist.github.com/jbogard/aec78a82d3b563039338#file-queryhandler-cs), he's new'ing up the model class in his handler, setting some properties, then setting the rest of the properties using data from his queries:
```
public Result Handle(Query message)
{
    var model = new Result
    {
        CurrentSort = message.SortOrder,
        NameSortParm = String.IsNullOrEmpty(message.SortOrder) ? "name_desc" : "",
        DateSortParm = message.SortOrder == "Date" ? "date_desc" : "Date",
    };
...
```

I'm probably missing something here b/c I'm new to the codebase and new to MediatR, or a combination of both.

Either way, if Shouldly and MediatR is something the allReady project has decided on, then I'll just get started on the refactoring starting with HomeController.

**Comment by mikesigs** [comment]
You're absolutely correct about there not being a check for null beforehand. I could probably remove it altogether if it's truly not needed. But in other cases these kinds of checks will be needed, and there's got to be a way of handling it that doesn't require duplicating that checking code in all/any controller methods. Read the comments on [the post I mentioned earlier](https://lostechies.com/jimmybogard/2015/05/05/cqrs-with-mediatr-and-automapper/). There's some useful stuff in there too.

I'm going to re-visit my approach a bit with MediatR too. I didn't read the above article before the Hackathon. And I think it could use a bit of changing WRT how I'm passing/creating the Command objects. Jimmy just uses the ViewModel/Command passed to the Controller, whereas in many places I am creating a new Command object inside the controller and sticking on the UserId, etc. I don't really like that. 

As for whether or not to use Shouldly... I think it may simplify things for new contributors. But then, I've been using some manner of "Should" framework for testing in all of my projects for years. I've never been much fond of using Assert.Bla(). As for whether we need explicit permission before introducing a new framework.... that I don't know.

**Comment by mikesigs** [comment]
@tonysurma How do you go about deciding when to add a new framework to this project? How do you feel about using [Shouldly](https://github.com/shouldly/shouldly) to assist in writing unit tests?

**Comment by mgmccarthy** [comment]
@mikesigs, either way, I'm on board, Shouldly or no Shouldly. Thanks for reaching out someone who can answer this question for us.

Looking at HomeController, the one place I could move to MediatR is the Index action method. However, Id' like to submit my first PR with the tests I've written, and once that is checked in, I'll refactor HomeController to MediatR. The good part is I'll have all the unit tests already written and passing, so that can help me refactor to sending a request for the data.

Thanks

**Comment by tonysurma** [comment]
In short, we balance the complexity, dependence & _another thing_ "cost" of adding a library or framework against the ease of use, code reduction, etc. "benefits" from using it.  From my quick review of this it appears this isn't a different or conflicting framework for testing and is instead one for ease of assertion work so it is 'complementary' to xUnit and also means that folks can use Shouldly or not in their unit tests.

Therefore given those points using it should be a good addition and thanks for the contribution and discussion and checking in to make sure the addition fits with the project plan @mgmccarthy and @mikesigs

**Comment by mgmccarthy** [comment]
@mikesigs, let me know when you install Shouldly via NuGet. I'd like to try to work with the framework. For now, I'm working on refactoring to MediatR on the HomeController. @tonysurma @mikesigs, do either of you know who installed MediatR for use in the solution? If so, was there any type of convention they wanted us to follow for naming our our Query and Model classes we use with our Handlers? Thanks

**Comment by tonysurma** [comment]
For Mediator I would talk to @misterjames I believe

**Comment by mikesigs** [comment]
@mgmccarthy When I do install it, it will be in my own fork for now. I also don't anticipate having time to push anything here until the weekend. Please feel free to install it if you want. I'll just rebase anyways and handle any conflicts.

**Comment by mgmccarthy** [comment]
@tonysurma @migsigs @MisterJames @SeanFeldman. 

I installed the xUnit runner extension for ReSharper 10 Ultimate the other day (b/c I'm tired of using MsTest to run the xUnit tests). I'm using Visual Studio 2015:

![xunitextensionforreshaperinstalled](https://cloud.githubusercontent.com/assets/2428993/13515888/1ca9e8f0-e183-11e5-9d84-bd888b564387.PNG)

yet when running the unit tests in ReSharper I get the following error pop up twice (I have to hit the "Ok" button between each error dialogue):

![xunittestrunnerfails](https://cloud.githubusercontent.com/assets/2428993/13515907/458a86da-e183-11e5-98d2-570aae60eab5.PNG)

I've poked around a bit online, but there is not much to go on. Was wondering if anyone else was using this same setup (ReSharper 10 Ultimate and xUnit extension) and was running into a similar problem?

ReShaper works perfectly for running NUnit tests.

**Comment by mmoore99** [comment]
@mgmccarthy I had the same problem.  I think it has to do with the Resharper plugin for xunit not being compatible with asp.net core.

**Comment by SeanFeldman** [comment]
@mgmccarthy yep, same thing here. NUnit works, xUnit doesn't.
@mmoore99 is spot on.

Two things:

#### Generating assemblies

By default DNX/Core doesn't emit assemblies.
![image](https://cloud.githubusercontent.com/assets/1309622/13518551/8d4f9e20-e18c-11e5-8695-d44c2937a749.png)

`Produce outputs on build` needs to be enabled (I think)

#### Output path

 When it's failing, it's looking for the unit tests assembly under
`\artifacts\bin\AllReady.UnitTest\AllReady.UniteTest.dll` 

when DNX produces this assembly under
`\artifacts\bin\AllReady.UnitTest\Debug\dnx451\AllReady.UnitTest.dll`

Guessing that it's the xUnit adapter that doesn't know how to resolve DNX assemblies.

**Comment by SeanFeldman** [comment]
From R# xUnit author:
> DNX isn't supported right now

Will need to wait for [this ](https://github.com/xunit/resharper-xunit/issues/38) to be resolved :sunglasses:

**Comment by mgmccarthy** [comment]
Thanks for digging into this a little deeper @mmoore99  add @SeanFeldman. 

@SeanFeldman, sounds like you tried checking "produce outputs on build" in the project properties of AllReady.UnitTest yet it still didn't work based on the [xUnit Repo-Issue #38](https://github.com/xunit/resharper-xunit/issues/38)? If that's so, I'll keep begrudgingly using MSTest for now.

**Comment by SeanFeldman** [comment]
@mgmccarthy correct. It needs to be done by xUnit adaptor. Until then, the
amazing mstest ui will do.

**Comment by mgmccarthy** [comment]
@tonysurma @mikesigs @MisterJames @SeanFeldman @mmoore99

for those of you using ReSharper Ultimate 10.1, there is an EAP of ReSharper 2016.1 (that's 10.1, they changed their versioning) that supports xUnit: http://blog.jetbrains.com/dotnet/2016/03/17/resharper-ultimate-2016-1-formerly-10-1-eap-6/. I'm not too sure how "safe" if it to install the EAP... I'll probably hold off until the official, finalized release, but just wanted others to know.

**Comment by mmoore99** [comment]
@mgmccarthy the Jetbrains  blog states:

> One thing to note is that this build does not yet support running tests for DNX projects, this will hopefully be included in a future build.

Does that mean it would not work with `allReady`?

**Comment by mgmccarthy** [comment]
@mmoore99, yeah, your' right, the upgrade will not work for allReady. I'm deleting my original comment. Just waiting for someone to get xUnit running w/ReSharper for DNX projects.... anyone. MS Test is driving me crazy.

**Comment by mikesigs** [comment]
As an alternative to running the tests in Visual Studio you could always run them from the command line using `dnx test`. 

You can run your tests continuously this way using nodemon. First, install nodemon `npm install -g nodemon` then run this command (from the Web-App folder) 
```
nodemon -e "cs,json" --exec "dnx -p ./AllReady.UnitTest test"
```

**Comment by mgmccarthy** [comment]
@mikesigs thanks for the tip. Devs like me are spoiled by ReSharper... I'll give nodemon a shot

**Comment by rmcc13** [comment]
I am working on unit tests for `TaskStatusChangeHandlerAsync` via #787

**Comment by tonysurma** [comment]
@mgmccarthy should this still be open and/or thoughts on a way to document what is left open?  thanks

**Comment by mgmccarthy** [comment]
@tonysurma we should close this "umbrella" issue and move to an issue per test class approach so we can track this.
