### ISSUE TITLE
Stubbing unit tests to allow easy `up-for-grabs`

### ISSUE THREAD

**Issue by SeanFeldman** [HTBox/allReady#620]
While talking to @mgmccarthy have realized that we've got lots of issues about [unit testing](https://github.com/HTBox/allReady/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unit) and an overarching issue that is [an epic](https://github.com/HTBox/allReady/issues/59) that don't really encourage people to easily start testing. Either because prerequisites of knowing what the system is doing are too complicated, or simply because there expected behaviour is not quite clear.

The suggestion is following: stub unit tests using some sort of BDD style to describe what should happen and tag it with `up-for-grabs`. This will also allow newbies like myself to contribute w/o being confused by lack of project knowledge or being intimidated that I miss the needed info to work on items. Project veterans could help by providing those stubs (_not_ pointing at anyone like @tonysurma or @MisterJames at all :smiley:).

An example: [OrganizationApiController: adding unit tests](https://github.com/HTBox/allReady/issues/615) could be stubbed as following:

`OrganizationApiControllerTests.cs`

``` c#
[Fact]
public void Can_get_contact_information_for_a_requested_contact_id()
{
}

[Fact]
public void Contact_information_is_returned_in_json_format()
{
}

api/values/5/Contact
[Fact]
public void Contact_information_action_is_only_available_to_admins()
{
}

// etc.
```

The least this will do is facilitate conversations around details clarification.

**Comment by tonysurma** [comment]
After a quick glance this looks good to me, pinging @BillWagner @mheggeseth @dpaquette @MisterJames for their thoughts

**Comment by mgmccarthy** [comment]
@SeanFeldman I have already submitted a PR for OrganizationApiController unit tests (Issue #616) but I agree with what you're proposing.

This extends beyond controller unit tests too. There are many handlers that need unit tests, and based on complexity, some ViewModels as well.

That being said, I am currently working on adding unit tests for ActivityAdminController (Issue #617). Instead of writing the unit tests, I can stub them out then submit a PR. That way, we can get others pitching in writing unit tests

**Comment by BillWagner** [comment]
I agree. I think this is a good organization.
