### ISSUE TITLE
6.1.2.2	Entity Relationships and definitions have (possibly) shifted a bit – P1

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#706]
- [ ] Campaigns are made up of one or more Events
- [ ] Events are made up of one or more Tasks & Events can span more than one day but a Task cannot
- [ ] A Task is a unique combination of skills & time – therefore a task designates volunteers needed for all of a single timeframe with all of requested skills & further if you need to have different skillsets OR different timeframes you need more than one task
- [ ] Volunteers are assigned to a Task either by volunteering directly or by assignment by an Organizer
- [ ] An Itinerary (for Itinerary Type Campaigns) is a collection of volunteers called a ‘team’ (from more than one Task in the same event that have the same timeframes but different skillsets) and a collection of requests (from the same campaign the Tasks for volunteers are from) to which they are assigned to deliver

**Comment by stevejgordon** [comment]
@tonysurma Can I just check, in all cases should tasks now be limited to a single day? For example...

Task 1 - May 7th 2016 - 8am to 10am
Task 2 - May 7th 2016 - 10am to 1pm
Task 3 - May 8th 2016 - 6am to 8pm

and for all event types never

Task x - May 7th 2016 to May 15th 2016

**Comment by robrich** [comment]
@tonysurma: on today's stand-up you clarified that a task was a unique set of skills, time, and place.  In the bullets above, it notes only skills and time.

**Comment by tonysurma** [comment]
That is cuz place isn't ' real thing' in our system (and shouldn't be) so that one is more a use concept while skills and time exist in our system

**Comment by stevejgordon** [comment]
@tonysurma - I'm starting to preen some of the older milestone issues. I think with the bits that have been added over the last few months we have this basically completed...

**Campaigns are made up of one or more Events** DONE

**Events are made up of one or more Tasks & Events can span more than one day but a Task cannot** DONE - Clarification - Tasks and Events span multiple days, Itineraries are limited to a single day.

**A Task is a unique combination of skills & time – therefore a task designates volunteers needed for all of a single timeframe with all of requested skills & further if you need to have different skillsets OR different timeframes you need more than one task** I believe this is DONE

**Volunteers are assigned to a Task either by volunteering directly or by assignment by an Organizer** Since removing the concept of an event signup we currently don't have a list of potential volunteers to assign directly to a task. At the moment a volunteer must first volunteer for the task. Is this correct or does this need further discussion?

**An Itinerary (for Itinerary Type Campaigns) is a collection of volunteers called a ‘team’ (from more than one Task in the same event that have the same timeframes but different skillsets) and a collection of requests (from the same campaign the Tasks for volunteers are from) to which they are assigned to deliver** DONE

**Comment by stevejgordon** [comment]
@tonysurma bump 😄
