### ISSUE TITLE
DateTime issue on loading Campaigns page 

### ISSUE THREAD

**Issue by sudhakarssd** [HTBox/allReady#710]
Exception on loading campaigns page for admin login. **" ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. Parameter name: offset"**
Exception occurred on  /Areas/Admin/Views/Campaign/Index.cshtml at line no. 56
 `@if (item.StartDate != DateTime.MinValue)`

Error is due to difference in local system timezone. It might be a good idea to use ToUniversalTime()
 `@if (item.StartDate != DateTime.MinValue.ToUniversalTime())`

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames @BillWagner 

what is the approach to Utc vs. local time for allReady? For example, I see that Campaign stores a `StartDateTime` and `EndDateTime` as well as a `TimeZoneId`. Are the `StartDateTime` and `EndDateTime` stored as UTC or local?

After reading this bug, then tracing through how we handle utc based conversions in the system, it seems a bit all over the map. We're using DateTime.Now in views, models, controllers, handlers, and DateTime.UtcNow in other places...

What is the expectation of storing DateTime values in the entities themselves? Are these DateTime values stored as utc or local time?

When reading these values, do we convert to local time based on the stored utc time + timezone values? What about writing the values? My assumption is the creation of entities that have start and end date would be submitted in local time, then we translate to utc before storing it?

**Comment by tonysurma** [comment]
I will let others chime in and add but from a functionality point of view:
All times should be displayed in local times relative to time zone of the campaign (much like flight times should all be displayed local to airport time zone metaphorically).  To make a fine point if Tony in Central time zone looks at campaign in Pacific time zone then it should show times in Pacific time zone not in central.

In my mind that means gathering and storing as UTC and rendering relative to time zone of campaign but up for discussion.  If you find a bunch of issues with that being out of pattern we could create them as issues for 'jump-in'

**Comment by stevejgordon** [comment]
I'm not fully clear on date handling myself but since we are using DateTimeOffset for the storage that should carry the timezone for the date with it and allows for conversion to from UTC time as well. It might be useful to think about any repeated datetime calculations and whether we can provider some kind of abstraction around it and a class to manage any date time related work. I've yet to dig into it in detail though to see what we're doing where.

**Comment by mgmccarthy** [comment]
@tonysurma  @stevejgordon. 

My initial approach would be to store `DateTime`, not `DateTimeOffset` in the db. All `DateTime`'s should be stored as UTC. Any field that stores a DateTime in the db as UTC should be renamed to:
[field_name]Utc.

I have an idea on a provider pattern that would allow us to change the `DateTime` from UTC to local time when retrieving info from the database for display purposes and vice-versa for submitting data in a write operation, where we'd convert from local time to UTC time before writing/updating data.

Here's a basic idea of the API:
```
public interface IConvertLocalTimeToUtcTime
{
    DateTime ConvertLocalTimeToUtc(string timeZoneId, DateTime dateTimeUtc);
}

public interface IConvertUtcTimeToLocalTime
{
    DateTime ConvertUtcTimeTo(string timeZoneId, DateTime dateTimeUtc);
}
```

These interfaces would be injected into classes that need them... I'm thinking mostly controllers/handlers. 

Right now, we have duplicated code across the codebase that deals with UTC to local and local to UTC conversions, and the use of DateTimeOffset is making that code more invovled than it needs to be.

I know this is not a P1 item, but I started a spike a while ago, but haven't worked on it in awhile.

**Comment by stevejgordon** [comment]
@mgmccarthy This sounds good to me. If this ends up being the final solution, I'm happy to assist with any sub-tasks if you need me to. If you're free tomorrow for the standup perhaps we could touch on this with the project owners and confirm the final pattern.

**Comment by mgmccarthy** [comment]
@stevejgordon, I unfortunately won't be able to make stand up tomorrow (but on most Saturday's, I am available, just not tomorrow). Maybe we can collaborate on it together using Gist. There will be a good amount of work, like handling the EF migration file when the names and data types of the properties that are currently DateTimeOffset are changed to DateTime, and other stuff I'm not thinking of that I probably will need help with.

**Comment by stevejgordon** [comment]
@mgmccarthy Sure, sounds good.

**Comment by robrich** [comment]
Date and Time are hard -- especially when crossing timezones.  See also http://hanselminutes.com/485/the-problem-with-datetime-nodatime-with-matt-johnson and https://www.pluralsight.com/courses/date-time-fundamentals.  I'm concerned about converting back and forth between UTC because "local time" to the server isn't usually what you expect.

**Comment by vishal123** [comment]
My 2 cents:
- DateTime should be stored in UTC and offset as appropriate during rendering.
- DateTime should be stored as ```DateTime``` and not ```DateTimeOffset```
- No need to postfix DateTime fields with 'Utc'

**Comment by mgmccarthy** [comment]
a quick implementation idea would look something like this:
```
public class UtcToLocalTimeConverter: IConvertUtcTimeToLocalTime
{
    public DateTime ConvertUtcTimeTo(string timeZoneId, DateTime dateTimeUtc)
    {
        TimeZoneInfo systemTimeZoneById = TimeZoneInfo.FindSystemTimeZoneById(timeZoneId);
        return TimeZoneInfo.ConvertTimeFromUtc(dateTimeUtc, systemTimeZoneById);
    }
}
```

another part of the implementation is we would add a `string TimeZoneId` to any model that needed it.

we `[Require]` TimeZoneId on creation for models that have it:
![image](https://cloud.githubusercontent.com/assets/2428993/15425733/51fbf892-1e58-11e6-95a1-cb7704e33722.png)

@robrich, I'm not going to be able to listen to the podcast and watch the pluralsite video today, but is any particular reason we cannot rely on "local time" (aka, DateTime.Now) on a given server in a certain time zone to return the correct local time?

@vishal123 the reason I'm proposing suffixing DateTimeFields with "UTC" is so the developers contributing to the project aren't left guessing (or incorrectly assuming) when they see a property on a model like this:
`public DateTime StartDate { get; set; }`

that it's a local time. Since .NET does not have a `DateTimeUtc` type, the suffix added to `DateTime` fields explicitly shows anyone who wants to contribute that the values stored in those `DateTime` fields are in UTC (and therefore, would need the conversion when reading/writing).

**Comment by vishal123** [comment]
Looks good. 👍 
That timezone select list could also be made into in tag helper.

**Comment by stevejgordon** [comment]
@mgmccarthy Might also be worth us looking at http://nodatime.org/ - Heard about it dotnetrocks a long time back. Not dug into it in depth but putting it here as a reminder to myself!

**Comment by dpaquette** [comment]
Duplicate conversion code is related to #410

**Comment by tonysurma** [comment]
@stevejgordon @mgmccarthy is this still a thing?

**Comment by mgmccarthy** [comment]
@tonysurma  I"m not too sure if the actual PR (first comment) is still a thing or not, but the conversation that followed about DateTime vs. DateTimeOffset has been decided and we've already done the work of abstracting the DateTimeOffset operations.

**Comment by dpaquette** [comment]
this can be closed
