### ISSUE TITLE
'PostalCodeGeo' and 'Locations' Tables

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#752]
Changes were made in PR #727 to remove the hard link between locations and the PostalCodeGeo table. This has made adding campaigns and events easier since previous behaviour meant that unless you specified an exact match for the fields, you were unable to add a campaign or event.

Locations are now no longer tied to that table with a relationship. Adding a new campaign with a new location simply creates a record only in the Locations table.

I would like to open this issue to discuss/verify what should actually happen for addresses. At the moment other than seed data I cannot see that the PostalCodeGeo table will be updated at all. Is this table now redundant? If so we could remove it from the code. If not, how should it be used?

Also, adding two events with the same address results in two rows in the Locations table with the exact same details (other than ID). If we want reuse of the locations, do we need new logic to check for an existing address first when adding a campaign/event. If one exists, it uses that location, otherwise it creates a new one.

@tonysurma @MisterJames - I see that you were both involved in the prior PR. Perhaps you can re-confirm exactly what the behaviours should be in each location related scenario and then we can split out any cleanup issues we need?

cc/ @mgmccarthy

**Comment by mgmccarthy** [comment]
First, thanks @stevejgordon for tracking that bug down and fixing it!

It looks like `CheckValidPostcodeQueryHandlerAsync`still reads from PostalCodeGeo, but besides that, I do not see any other usages of PostalCodeGeo in the system. In fact, the command that `CheckValidPostcodeQueryHandlerAsync` handles is not longer being sent by anything, so this handler and command should be deleted. My two cents on the PostalCodeGeo table is if its not used, we should drop the table. We can always add it back to the code later if we need to.

As far as the Location table is concerned, it looks like there is an `Id` property on the entity, which means this is a separate table with it's own primary key. Looking at how Location is used, however, makes me think if we should change the way we're storing the data in the database to a [Value Object](https://lostechies.com/jimmybogard/2008/05/21/entities-value-objects-aggregates-and-roots/) (scroll down to the explanation of a Value Object). 

The question we need to answer functionally is would a user ever do any CRUD based ops against a Location outside the context of an "owning" aggregate root? Right now, looks like the Campaign, Event and Organization entities use (aka "own") Location. My guess is that if we're working with a Location, then we're doing it in the context of a aggregate root.

If we, so we can change Location to a Value Object (which means the data will most likely will be stored in the same table as Campaign, Event or Organization) and changes to the data in those fields will only be done in the context of those "owning" entities. If you want to change Location in any way, you need to load the owning aggregate root.

As far as repeated data in Location (however we  end up storing it)... I don't think it's a bad thing to have two rows with the exact same data. IMO, since Location is always owned by an entity, then repeated data should be of no concern and the trade-off to make the data unique row-by-row does not outweigh the extra code we'd have to write and maintain in order to enforce that.

**Comment by tonysurma** [comment]
In short what you are describing @stevejgordon is right - it is now redundant and unneeded and no worries about multiple entries in Location that are now same

**Comment by stevejgordon** [comment]
@tonysurma Thanks. What should the different user journeys/stories around locations be? I know there was a postcode search feature previously that got hidden/removed. From the standup @MisterJames talked about using Google API and I believe users are likely to need to perform radial searches and task mapping etc. in the future? If so, I think we need to consider those requirements into any current design/code changes. It might be useful to store lat/long on addresses for example. When a new address is added we could use the Google API to get the geo-coordinates and then store them so we don't have to pull them each time we need them. EF 6 had a radial search feature I think, although not sure it's made it into EF Core yet!

I assume it might also be nicer UX if we pre-fill the address from the parent campaign when creating a new event and also for tasks (same address as the event). The organizer could update / change it but it could save time in some cases?

Also, perhaps we'd need a general address autocomplete if a user starts entering a prior address? Anything to save them some time and make the experience easier.

@mgmccarthy You're view on making addresses feels sensible to me. Having a separate table for the locations, which really have no need to be shared, feels a little unnecessary. An event is taking place somewhere and if that address changes we shouldn't expect any other entities, sharing that address to be updated automatically.

The only query I have over the approach is if we need to be able to easier perform location searches as we may have to scan into many tables if we store with the campaign, event, org etc. However the current single table, with a 1 to 1 relationship with the other entities would be easier to search on?

I hope that makes sense!

**Comment by mgmccarthy** [comment]
@stevejgordon, I didn't know about the searching feature that is why I recommended the value object approach to storing addresses (basically, and Address cannot exist outside of the context of its aggregate root: Campaign, Event, Organization). 

If, once an Organization or Event is created in the context of a Campaign, those addresses can evolve on their own, I think it's still possible to consider the value object approach, BUT, as you pointed out, where this introduces complexity is on the search site... where we're have to search multiple columns in those three tables if a user is a doing a search to find an Organization or Event close to them. It's not that it couldn't be done, it's just that the query would not be as straight-forward

I'd say stick to the middle road for now, keep Location in it's own table, and allow dupes (which isn't a big deal IMO). I like the idea of adding the lat/long to the table and using Google API to get geo-coordinates to store with the table. 

If we go that route, we need to be cognicant that we've created a reliance on an outside network call/3rd party in order for the creation of anything with an Address in our system. For example, the Google API not responding/timing out should not prevent us from creating Campaigns, Organizations, Events...

**Comment by stevejgordon** [comment]
@mgmccarthy Yep, good point on the 3rd party coupling. I'm tackling something similar on a new work project and we're looking at self contained micro-services for such work. That would probably be overkill here but we could implement something like https://github.com/App-vNext/Polly to set some retry policies etc.

**Comment by mgmccarthy** [comment]
@stevejgordon, cool library! I'd like some time to check it out at some point. Have you used it all?

I work with NServiceBus everyday so I pretty much think async at this point and take retries, error queues and durable messaging for granted.

It is cool to see other open source libraries tackle the very real problem of 3rd party integration especially when calling that integration from withing a transactional boundary of the current system.

**Comment by mgmccarthy** [comment]
@stevejgordon, Polly could also be used for all our messaging as well... emails, text messages, etc... we don't want a transaction to fail b/c the underlying delivery mechanism for an email is down. I'm not too sure if the underlying mechanism for email sending (which looks like it uses Azure queues?) will work like Polly or not.

We could also use it for incoming integrations like #700. This allows us to retry, and use a "back off" policy to getting the data we need if the web service is not responding, slow, etc...

**Comment by stevejgordon** [comment]
I think this can be closed out now.
