### ISSUE TITLE
Validate if new users are required to complete their name

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#840]
This is required so we can display their name on itineraries and within the application.

@tonysurma - A couple of questions around this

1. Currently name is a single field. Would this be better if split to forename and surname?
2. Should we prevent task signups until someone has provided their name? A downside would be a slighter bigger barrier to entry for volunteers. An alternative is we promote completing their profile but don't' enforce it. We'd render empty names for those we don't have.

**Comment by tonysurma** [comment]
1. Yes
2. I think we need to enforce name or we prompt but don't enforce 

@OhMcGoo, @adedonato what do you think?

**Comment by adedonato** [comment]
1. Yes, I think splitting the name into forename and surname field would be best. 
2. I think we should enforce names.

**Comment by tonysurma** [comment]
Thanks @adedonato !

**Comment by stevejgordon** [comment]
Thanks @adedonato and @tonysurma - For a regular signup this should be quite simple as we can expose the name fields on the register form as required.

I need to double check the signup flow from Facebook etc where this may not always have this data available. I think the flow brings them to a page to complete their account so this could be quick simple. I need to setup my dev machine with Facebook to test that though.

Currently there is a warning for a user who does not have their profile completed in the top right, however a use can still volunteer without setting their name.

The profile warning also occurs if no phone number is set. This seems sensible since this is a key tool for contacting a volunteer during an event. Setting a phone number requires a verification of a code sent to the phone.

Two options
1. We include the forename, surname fields in the volunteer box, if they are not set in their profile. This could update their profile behind the scenes. This is fine for the name but less slick for the phone since we require it to be validated with the code.

2. We provide a warning that they must complete their profile first and a link to the manage profile screen? We then allow the normal management to take place and once complete they can volunteer. This is easier with the current code and structure as it requires less work to change. It might be slightly more painful for the volunteer though.

Followup:
Since we pretty much expect a phone number for a user, should we include that as required on the register form? Not a good idea if you could have volunteers without a mobile phone who may register. Although, in that case the management of them may breakdown later anyway?

**Comment by tonysurma** [comment]
Could we do Option 1 and redirect to the validation screen if they provide a phone or is that too crazy?

Alternatively Option 2 could work but it feels 'less slick' than Option 1 and more painful as you said.

Lastly yes, mobile phone number should be required.  at this point that shouldn't be a huge impediment for near turn scenarios and we can always adapt/relax this in the future

**Comment by stevejgordon** [comment]
@mgmccarthy Perhaps this is something you could look at. I think first part would be to ensure that after a social (Facebook) registration that the page where they provide their email as username also requires first and last names? At least then our registration flows would ensure we should have this data. It may even negate the need to complete option 1 above. That said; we probably need to review the mobile phone handling and consider all scenarios.

**Comment by mgmccarthy** [comment]
@stevejgordon I can take a look.

@tonysurma My two cents on what should be required at registration is only email address. The phone number is not something we need, but w/out a legit way to communicate with the volunteer, then the site will not be that useful. 

I might be saying this out of turn, b/c I don't know enough about the volunteers to know if expecting them to all have smartphones that get emails vs. regular phones (or smart phones) that get SMS is something we need to worry about.

SMS is much less asynchronous than email could potentially be (especially if the volunteer is not getting email pushed to their phone but rather fetches when they feel like it), so SMS is more push and immediate communication, which sounds like what we're after.

As far as first/last name, any time this is missing, we could replace with the word "Volunteer", but we need to write code for that. However, would requiring them to enter a first name and last name at the point they register with the site be a barrier to entry for them? I remember hearing in a standup once we want to make it as easy as possible for volunteers to volunteer. 

The less of them we ask up front, the more likely they will be to volunteer and go through a simple registration?

Since I've never worked with the Facebook API for sign-in, this research might take me awhile. We only need to research it if we truly deem that first name/last name MUST be required in order to volunteer for a task

**Comment by tonysurma** [comment]
Based upon the Usage scenario we need first and last email and phone as required.

In fact if we were to drop anything it would be email from a usage scenario point of view - we aren't doing it but just pointing out for showing how key sms is.  Thx

**Comment by mgmccarthy** [comment]
@tonysurma @stevejgordon I'll be working on this one next b/c it's P2. I have #919 and #920 on my "backlog" b/c they're P3, but any developer should be able to work on those two if they want to. Up to you if you want to "unassign" me.

There is also #921 which is P2, so that should probably be worked on before #919 and #920.

Do we have a P2 "date"?

It might take me awhile to figure out how to get the Facebook login working... I'll ask questions as I go along

**Comment by mgmccarthy** [comment]
@tonysurma please assign me to

**Comment by mgmccarthy** [comment]
@tonysurma, registration page is done requiring first name, last name and phone:
 
![image](https://cloud.githubusercontent.com/assets/2428993/16339550/573ffac4-39f1-11e6-9599-29b2688d0f6b.png)

If you want, I can submit a PR and get this into the codebase.

However, I just tried to start looking into the Facebook login:
![image](https://cloud.githubusercontent.com/assets/2428993/16339479/e28c403e-39f0-11e6-9ba0-0812e6925d0b.png)

But I'm getting this error after clicking it:
![image](https://cloud.githubusercontent.com/assets/2428993/16339505/ff48fd16-39f0-11e6-83cf-324ccb2f512a.png)

having never worked with other OAuth providers before, I'm not too sure how to start getting this hooked up. My guess is that AllReady will be given some type of FaceBook appid/secreet, and those crendentials need to be included in the http request made to this URL:
https://www.facebook.com/v2.2/dialog/oauth?client_id=%5BfacebookappId%5D&scope=email&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A48408%2Fsignin-facebook&state=CfDJ8ETSwU1i6RtMhcUjB9n1ZCdKL0h_PiNj_M0qy-BRzoJx6VoTQJYnTDFTrQIBoJ7VScvLfAtGboQ_0-F-okS_eJU3NtNRuF0nvG2d7iSTV1iqH0ZmcqKr4vb3oj61sOhyVwn4zmWmR2M-xHr2f1e-5xanbLqNn2TYNUHNURVcQeWmedIyMlbX7zAXn3ip3Fm-tnmsXFXSWNZ5IC0UbzfTcyNTyhk2oN3_AGM_SotSWhambIoa9YuN7IJFFD9KfQtqTgweGTEAxyPt3s5rIeZGDL4sLns9UWFoem9vMCvoYcNEN4AplLfW1v9tcx3nPH-JZA

Have we actually ever tested any of these oauth logins or have any of them every worked? How important are they to have up and running for P2 itmes?

**Comment by stevejgordon** [comment]
@mgmccarthy There's a few things you'll need to do to get Facebook login setup in dev.

1. You'll need to setup an application under Facebook in the developer area.

![image](https://cloud.githubusercontent.com/assets/3669103/16339843/c279329e-3a1c-11e6-8d91-3f79d834a252.png)

You'll then need to register some appSecrets or environment variables locally which set the appSecret and appId. These are set with placeholders in the config.json.

![image](https://cloud.githubusercontent.com/assets/3669103/16339727/294c29be-3a1c-11e6-8a8e-1820a7283a51.png)

The .net core configuration gets setup in Startup.cs and describes an order of places that the app will check for settings. Any settings lower down the list will override those set in configs earlier on.

![image](https://cloud.githubusercontent.com/assets/3669103/16339756/4d3713e8-3a1c-11e6-88f7-2a6868b2e90e.png)

This is quite a nice setup. Basically if you setup environment variables for Authentication:Facebook:AppSecret and Authentication:Facebook:AppId these will be picked up and configured into the configuration object.

It takes a little while to get it all going but I have managed it and logged into the site with my Facebook account.

It's up to you. If you prefer to put in a PR for this first piece and a new issue for the social login stuff I'm happy to do the coding since I have Facebook working. If you want to try and get it setup and working, feel free. A good chance to play with the new .net core config stuff!

**Comment by mgmccarthy** [comment]
@stevejgordon, if we have time, I'd like to try to get the facebook auth set up locally. Since I've never done it before, I'd like to learn.

**Comment by stevejgordon** [comment]
No worries. Happy to chat through it if you need further support. I think user secrets changed a bit between rc1 and rc2 so I ended up using environment variables on my dev machine at home.

**Comment by mgmccarthy** [comment]
@tonysurma @stevejgordon

two things I've seen so far. 

One:
When registering via the regular sign-in form on AllReady, we are not sending a message out to verify the phone number provided (we are sending out an email verification for the email provided when registering). Do we also want to send out the verification of the phone number when registering as well? Right now, the user can verify their email, return to the site, and then click on the "Verify" link next to their phone number to have an sms delivered to their phone container the verification code:
![image](https://cloud.githubusercontent.com/assets/2428993/16343078/322f2de2-3a03-11e6-96e7-71c60f433378.png)

Two:
I have the Facebook login working now, and also enforcing the user provides their First and Last name as well as their phone number. However, after successfully logging in and having the user created in the AllReady system, we still are asking the user to verify their email with us. Is this the behavior we want for external login providers?

These are what the steps look like:

sign in with Facebook:
![image](https://cloud.githubusercontent.com/assets/2428993/16343112/5bb38276-3a03-11e6-852e-66b03ad46a88.png)

we're now asking for First Name, Last Name and phone number before continuing. Email is automatcially populated from the ExternalLoginProvider:
![image](https://cloud.githubusercontent.com/assets/2428993/16343146/8635f182-3a03-11e6-8f00-dd18fe40ce48.png)

ViewModel validation of fields we require for user registration:
![image](https://cloud.githubusercontent.com/assets/2428993/16343339/8d72f566-3a04-11e6-9fd6-e8a18e5fc8f9.png)

after registering and signing in,  coming back to ManageController and being prompted to confirm email and phone number:
![image](https://cloud.githubusercontent.com/assets/2428993/16343313/5f55e0bc-3a04-11e6-9c9b-fc7e1fbe988d.png)

**Comment by tonysurma** [comment]
Great research and thanks for digging in.

One: yes we should do phone as well.

Two: IF the email is provided by the provider (facebook, twitter, etc.) then we SHOULD NOT ask for verification.  However (if memory serves correctly)I think one or two of them do not provide email address and therefore we will need to ask for it and verify in that case.  So the code there may not have differentiated if the email came from the provider or not and did the lowest common denominator of always verifying.

Thanks again

**Comment by mgmccarthy** [comment]
@tonysurma  Sending verification for phone number during AllReady user registration should be easy to add, I'll to that in another PR.

For the external auth providers, right now, the code in the external auth section is vendor agnostic, so I'd need to do research into each of the external auths we're supporting in order to make sure the code runs correctly. I've only successfully run it using Facebook.

That being said, for P2, do you want to support all three, or just start with Facebook?

**Comment by mgmccarthy** [comment]
@tonysurma looks like Twitter API does not give out user email, but Facebook does. I'll see if I can pick up implementation for more of these providers next week.

**Comment by mgmccarthy** [comment]
@tonysurma, just to clarify the functionality of what was merged in #945. Currently, when authenticating via Facebook, we are NOT sending out a message to confirm email or confirm phone. For regular AllReady registration, we're sending out both messages at the point the user registers.

For Facebook auth, after authenticating, the First, Last, and Email fields are all prepopulated, and the user only has to fill out Phone:
![image](https://cloud.githubusercontent.com/assets/2428993/16356713/9183ab58-3ab0-11e6-8af9-8f18a3a2ecb2.png)

after they click register, we redirect them to the home page, where they can click on their manage account link and this is the page they will see:
![image](https://cloud.githubusercontent.com/assets/2428993/16356725/d18c19e2-3ab0-11e6-8121-35e281656a16.png)

I wanted to outline this for you, b/c regardless of which external auth provider we use, the user still lands on this page after authenticating with the external auth provider:
![image](https://cloud.githubusercontent.com/assets/2428993/16356713/9183ab58-3ab0-11e6-8af9-8f18a3a2ecb2.png)

and they're still required to fill out all four fields in order to continue registration with AllReady, **regardless of what information is made available to us for the given auth provider**. Again, Facebook gives us more info to pre-populate those fields, and Twitter gives us hardly anything (at least from what I've been able to figure out so far).

**I'm thinking since all auth providers use this form page, and since all four fields are required, we should still be able to send an email and sms confirmation message when they hit register.**

We should probably break this out into a separate issue, b/c it no long has to do with this issue (#840) at all.
