### ISSUE TITLE
Manage your account

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#883]
First name and Last name display names needed.

Currently does not show the labels with the spaces.

![image](https://cloud.githubusercontent.com/assets/3669103/16130908/467ce678-3403-11e6-86fe-b12cf3ce9458.png)

@mgmccarthy Not sure if this is resulting from my earlier mess. I don't think so as I reverted everything. I didn't notice this previously though. Perhaps just need some display name attributes on these fields.

**Comment by mgmccarthy** [comment]
@stevejgordon, I did put attributed on both of those do displa with a space. If they're not there o can add them once you get a clean build and submit a Pr

**Comment by mgmccarthy** [comment]
@stevejgordon, what page is this?

**Comment by mgmccarthy** [comment]
@stevejgordon, there seems to be something funky going on with my master branch... it's somehow picking up changes I've made to other branches I've created from it... and that does't make sense.

Until I can find a way back to what my master branch used to be, I might not be able to push to allReady

**Comment by mgmccarthy** [comment]
@stevejgordon, this was my fault. 

I didn't fetch/merge/rebase between the SplitUserNameProperty branch and commiting the OrganizeViewModelBranch. The OrganizeViewModel branch lost the Display(Name...) attribute on FirstName and LastName on the IndexViewModel, which is why the two fields are in the UI w/out a space between them.

PR #887 will fix this.
