### ISSUE TITLE
ViewModel folder organization under AllReady\Areas\ (low priority)

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#890]
this is low priority

- the Models folder should be renamed to ViewModels
- We should organize the ViewModels folder to have the name of the controller as a directory, and then all relevant ViewModel classes go under that directory.
- this is a similar refactoring to #857

**Comment by danielepo** [comment]
I noticed that the models in the Allready/Areas/Admin/Models folder are used to query the data and then are sent to the View:

![image](https://cloud.githubusercontent.com/assets/6214856/17514025/982a4e78-5e30-11e6-9a09-2f9886217bc7.png)

while the controllers that are not in the Admin area use a Model to query the data and then build a ViewModel and pass it to the view, like for example in the CampaignController

![image](https://cloud.githubusercontent.com/assets/6214856/17513940/3f2d554a-5e30-11e6-9c9c-4fa07d8db12b.png)

where

![image](https://cloud.githubusercontent.com/assets/6214856/17513958/543574d6-5e30-11e6-922d-c693971edb13.png)

and 

![image](https://cloud.githubusercontent.com/assets/6214856/17513969/60a84bc6-5e30-11e6-979f-9f55a372b8d1.png)

Is it ok to just reorganize the folder moving the files to subfolders or it would be better to create ViewModel objects? I don't think will be necessary because the Models are already highly specialized and not really shared across controllers but I wanted to get your opinion on this.

**Comment by mgmccarthy** [comment]
@danielepo 

How the ViewModel is built is irrelevant. The ViewModel may be built by a MediatR query handler, or as your code snippet above shows, it may be constructed by the controller from a model and then a ViewModel built from that model by some other means.

In a perfect world, all ViewModels would be built by MediatR handlers, and the controllers would simply pass back the ViewModel to the view (and I would like to see AllReady move in this direction going forward)

Right now, this is a hard pattern to use in AllReady because:
1. the same ViewModel is dragged across all action methods of a controller instead of a ViewModel optimized per PRG.
2. some ViewModels are shared across multiple controllers.
2. some ViewModels (as well as Models) contain extension methods that do all sorts of things they should not do (database calls). These extension methods are used by other objects that have no business interacting with said ViewModel.

Issue #994 is an example of this.

For now, I would concentrate on the renaming of the folder, the creation of sub-folders based on the controller and potentially renaming any classes that have the name "Model" in them to "ViewModel"

The term "Model" (at least in AllReady) refers to a class that is a representation of a database table. I find it confusing that we're using the term "Model" to refer to classes returned to the View when we're talking about items in \Areas\Admin, but the term "ViewModel" is used for classes returned to the View for items **not** in \Areas\Admin.

They should all be referred to/renamed to "ViewModel".

**Comment by danielepo** [comment]
@mgmccarthy  thank you very much for your explanation, I really appreciate it!

**Comment by mgmccarthy** [comment]
@tonysurma, this Issue can be closed
